group/members
traPtitech/Jomon pull request #443
Opened 2021-06-23 16:09 UTC by shota-aa

エラーがおきています

2021-06-23 16:20 UTC, cskd8 commented
traQにも投げましたが、いつでも見られるようにこっちにも

見た感じのレビューを投げておきます
- routerの実装はやりたいことがかけていていい感じです:thumbsup:ただ、まだエラーが出ている部分が多いので方針を示しておきます
    - model層にGetMembersを実装する
        - これはもう理解できていましたね:thumbsup:
    - ctxを修正する
        - これは少し難しいのですが、ctxには`c.Request().Context()`ではなく新しく作った`context.Background()`を用いてあげてください。`tag.go`を参考にしてみると良いです。contextの概念は[ここ](https://qiita.com/marnie_ms4/items/985d67c4c1b29e11fffc)などを見るとわかるのですが、少し難しいのでまだ理解できなくても大丈夫です。
    - 返り値を修正する
        - `c.NoContent`にmembersを持たせることはできなくて、JSON形式でレスポンスを返す時には`c.JSON`を使います。これも`tag.go`を参考に修正してみてください
- model層はまだ実装途中だと思いますが、現在気づいたことを投げておきます
    - これはGoのインターフェースという概念が関わるのですが、現在model層の実装では、GroupRepositoryにメソッドを登録して、group_impl.goのようにimplの中にメソッドを記述してあげています。また、メソッドにするために関数レシーバとしてEntRepositoryをもたせています。詳しくは[A Tour ofGoのMethods and interfaces](https://go-tour-jp.appspot.com/methods/1)を読んでみてください

2021-07-03 06:04 UTC, shota-aa commented
:groupIDをどのIDとつなげればいいのかわからないです。
traqが動かない。。。(-"-)

2021-07-03 06:48 UTC, cskd8 commented
そうしたら今度進捗会的な感じで今回のこのタスクを例にどのような実装になっているか説明＆実装をしてみる時間を取ってみるのはどうですか？Jomon/serverチャンネルで同様の話題あげるので、反応くれると嬉しいです！
Qが落ちてたのは...:cry:

2021-07-05 13:53 UTC, cskd8 requested changes
model層は良く書けています！routerの、echo周りの処理に対して曖昧な部分があるように見えるので、[echoの公式サイト](https://echo.labstack.com/)などを使って、わからない部分があったら調べながら実装していってみてください:thumbsup:

2021-07-05 13:53 UTC, cskd8 commented on docker-compose.yml
> +      - 8888:80
付け加えてもらってる中申し訳ないのですが、v2ブランチにもこの内容を導入していてコンフリクトが起きてしまっているので手元で使い終わったら消してからpushしてほしいです:pray:

2021-07-05 13:53 UTC, cskd8 commented on model/group_impl.go
> +	}
ぼくが貼ったコードが悪くて、こうするよりも以下のコードのようにしたほうが効率が良いのでそのように変更してほしいです
```golang
_, err := repo.client.Group.
    Update().
    Where(group.IDEQ(groupID)).
    AddUserIDs(userID).
    Save(ctx)
if err != nil {
    return nil, err
}
```

2021-07-05 13:53 UTC, cskd8 commented on model/group_impl.go
> +	}
ここも同様に以下のようにしてほしいです
```golang
_, err := repo.client.Group.
    Update().
    Where(group.IDEQ(groupID)).
    RemoveUserIDs(userID).
    Save(ctx)
if err != nil {
    return nil, err
}
```

2021-07-05 13:53 UTC, cskd8 commented on model/group_impl.go
> +	return err
これでもnilが返るのは確かなのですが、`return nil`と明示的にしたほうが良いのでそのように変更してほしいです。

2021-07-05 13:53 UTC, cskd8 commented on router/group.go
> +	Members []*Group `json:"member"`
ここと`MemberResponse`は同じ内容なので、統一をお願いします。

2021-07-05 13:53 UTC, cskd8 commented on router/group.go
> +	Members []uuid.UUID `json:"members"`
swaggerで変更してもらったように、JSONのフィールド名は`id`になったので変更をお願いします。それに伴って構造体のフィールド名も変更をお願いします。

2021-07-05 13:53 UTC, cskd8 commented on router/group.go
> +	return c.JSON(http.StatusOK, res)
これだとレスポンスは以下のようになると思います
```yaml
"3fa85f64-5717-4562-b3fc-2c963f66afa6"
```
これはswaggerとは一致していないので、修正をお願いします。

2021-07-05 13:53 UTC, cskd8 commented on router/group.go
> +	}
```yaml
{
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
```
を`model.User`にBindはできないと思います。それ用の構造体を用意する必要があります。

2021-07-05 13:53 UTC, cskd8 commented on router/group.go
> +	}
Bindの構造体のやつ。同様に修正をお願いします。

2021-07-10 12:41 UTC, shota-aa commented on router/group.go
> +	Members []uuid.UUID `json:"members"`
ID []uuid.UUID `json:"id"`
でいいですか？

2021-07-11 07:55 UTC, cskd8 requested changes
いい感じです！書き方の統一のために少し直してほしい部分があるので、修正お願いします！
それと、reviewの準備ができたらReviewersのところからもう一度reviewをrequestしてほしいのと、以前のreviewに対して修正で解決できたものはどんどんResolve conversationを押してもらって大丈夫です:thumbsup:

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +	members, err := repo.client.Group.Query().Where(group.IDEQ(groupID)).QueryUser().All(ctx)
書き方を統一したいです。
```suggestion
	members, err := repo.client.Group.
	    Query().
	    Where(group.IDEQ(groupID)).
	    QueryUser().
	    All(ctx)
```

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +	_, err := repo.client.Group.Update().Where(group.IDEQ(groupID)).AddUserIDs(userID).Save(ctx)
書き方の統一のやつと、下でSELECT文を発行して再度取得してくるのは効率が悪くて、以下のようにすれば同時にupdateしたUserを取ってこれます。
```suggestion
	created, err := repo.client.Group.
	    Update().
	    Where(group.IDEQ(groupID)).
	    AddUserIDs(userID).
	    Save(ctx)
```

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +	}
上記のようにすれば不要です。

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +func (repo *EntRepository) PostMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (*User, error) {
model層では`Post`ではなく`Create`としてください。
```suggestion
func (repo *EntRepository) CreateMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (*User, error) {
```

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +	_, err := repo.client.Group.Update().Where(group.IDEQ(groupID)).RemoveUserIDs(userID).Save(ctx)
書き方のやつ
```suggestion
	_, err := repo.client.Group.
	    Update().
	    Where(group.IDEQ(groupID))
	    .RemoveUserIDs(userID).
	    Save(ctx)
```

2021-07-11 07:55 UTC, cskd8 commented on model/group_impl.go
> +	return nil
これでも問題はないのですが、`return err`としてしまってもいいかも。好みの問題なので好きなほうで大丈夫です:thumbsup:

2021-07-11 07:55 UTC, cskd8 commented on router/group.go
> +	ID []uuid.UUID `json:"id"`
swaggerにはここは`id`ではなく`members`となっているので、そのように修正してください。

2021-07-11 07:55 UTC, cskd8 commented on router/group.go
> +	ctx := context.Background()
動作には全く関係ないのですが、書き方の統一で`PostMember`のように`ctx`の定義はmodel層のメソッドを呼び出す場所、今回では`GetMembers`の前においてあげたいです。

2021-07-11 09:44 UTC, cskd8 requested changes
`User`のとこはそもそも新しい構造体を`group.go`につくって、それで返してほしいです:pray:
なんども変わっちゃって申し訳ないです:pray:

2021-07-11 09:44 UTC, cskd8 commented on model/group_impl.go
> +	All(ctx)
```suggestion
	members, err := repo.client.Group.
	    Query().
	    Where(group.IDEQ(groupID)).
	    QueryUser().
	    All(ctx)
```
こんな感じでインデントを入れてほしいです。ほかのとこもお願いします。

2021-07-11 09:44 UTC, cskd8 commented on model/group_impl.go
> +	_, err := repo.client.Group.Update().Where(group.IDEQ(groupID)).RemoveUserIDs(userID).Save(ctx)
ここ忘れています。

2021-07-11 09:44 UTC, cskd8 commented on model/group_impl.go
> +	Save(ctx)
インデントおねがいします:pray:

2021-07-11 10:35 UTC, cskd8 requested changes
少しだけ変更をお願いします。

2021-07-11 10:35 UTC, cskd8 commented on model/group.go
> +}
Memberを表すのがこの構造体なので、名前は`Member`でいいかも

2021-07-11 10:35 UTC, cskd8 commented on model/group_impl.go
> +			All(ctx)
インデントが空きすぎちゃってる:sweat_smile:
VSCodeならタブのサイズ4でタブ1つです

2021-07-11 10:35 UTC, cskd8 commented on model/group_impl.go
> +			Save(ctx)
インデントのやつ

2021-07-11 10:35 UTC, cskd8 commented on model/group_impl.go
> +			Save(ctx)
インデントのやつ

2021-07-11 10:42 UTC, cskd8 approved these changes
LGTM:thumbsup:
まだマージしないで、さらにテストの追加もしてほしくて、まずは今のv2をrebaseしてほしいです:pray:
```sh
git checkout v2
git pull
git checkout group-members
git pull
git rebase v2
```
これでできるはず

2021-07-11 10:52 UTC, shota-aa commented
> LGTM👍
> まだマージしないで、さらにテストの追加もしてほしくて、まずは今のv2をrebaseしてほしいです🙏
> 
> ```shell
> git checkout v2
> git pull
> git checkout group-members
> git pull
> git rebase v2
> ```
> 
> これでできるはず

完了しました。

2021-07-11 10:53 UTC, shota-aa commented
これでpushすればいいんですか？

2021-07-22 14:42 UTC, cskd8 requested changes
テストはtag_impl_test.goの形式をそのまま真似するといい感じになると思います:thumbsup:

2021-07-22 14:42 UTC, cskd8 commented on model/group_impl_test.go
> +}
テストは、その機能ごとに書いてほしいです。この関数の名前でGetMembersとしていることからわかるように、この関数ではGetMembersが機能を正しく果たしているかをテストしてほしいです。詳しくはunit testで調べてみてください。

2021-09-03 13:42 UTC, cskd8 requested changes
成功するテストだけでなく、失敗するテストも書いてあげると良いです。例えば今回で言うと`CreateMember`の`group.ID`が存在しないグループのIDだったりするとエラーが返ってくるはずで、こういうところがちゃんとエラーを返せているかなどもテストしてあげたいです。

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +	t.Run("success", func(t *testing.T) {
統一するための`Success`にしてほしいです

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +	t.Run("sucsess", func(t *testing.T) {
typoしてます

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +	t.Run("sucsess", func(t *testing.T) {
ここもtypo

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +		budget := rand.Int()
`rand.Int()`を使ってもできるのですが、今回は`testutil`の中に`random`パッケージを用意しているので、`random.Numeric(t, 100000)`とかやってあげると統一できて良いです

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +		assert.Equal(t, member.ID, user.ID)
エラーをちゃんととって、`assert.NoError(t, err)`とかやってあげてください。ほかのテストも←をお願いします。
これ以外のエラー返す場所も`require.NoError(t, err)`とやってあげてくれるとなお良さ(ほかのとこではそういうとこも`assert.NoError()`になってるけど、これは良くないので後で直します)

2021-09-03 13:42 UTC, cskd8 commented on model/group_impl_test.go
> +    member, _ := repo.CreateMember(ctx, group.ID, user.ID)
インデントがおかしいです

2021-09-03 13:43 UTC, cskd8 commented
close #420

2021-09-11 15:26 UTC, cskd8 requested changes
これらのSuccessのテストだけではすべての状態をテストしているとは言えなくて、https://codecov.io/gh/traPtitech/Jomon/src/997946c8332ef01b49fcec3e7daf25109862a3f5/model/group_impl.go を見るとわかるようにテストでカバーできていない部分が多くあります。これらをなるべく全てテストできるようにテストの追加をしてください。v2ブランチの`tag_impl_test.go`などが参考になると思います。

2021-09-11 15:26 UTC, cskd8 commented on model/group_impl.go
> +	// "errors"
消してほしいです

2021-09-11 15:26 UTC, cskd8 commented on model/group_impl_test.go
> +		assert.Equal(t, got, []*User{})
別のテストに切り出してほしいです:pray:

2021-09-11 15:26 UTC, cskd8 commented on model/group_impl_test.go
> +}
`TestEntRepository_{{function}}`の形式なので、このようにメソッドが存在しないテストは作らずに、この例では`TestEntRepository_CreateMember`の中に入れてあげてほしいです。あと`falseMember`がなにを指しているのかわからないので命名を変えてほしいです。あとif文の部分もなにをしているのかわかりません。これは要するにやりたいことは`UnknownGroup`ということですよね？だったら以下のようにしてほしいです。
```go
func TestEntRepository_CreateMember(t *testing.T) {
	client, storage, err := setup(t)
	require.NoError(t, err)
	repo := NewEntRepository(client, storage)
~~~
	t.Run("UnknownGroup", func(t *testing.T) {
		t.Parallel()
		ctx := context.Background()
		user, err := repo.CreateUser(ctx, random.AlphaNumeric(t, 20), random.AlphaNumeric(t, 15), true)
		require.NoError(t, err)
		falseMember, err := repo.CreateMember(ctx, uuid.New(), user.ID)
		assert.Error(t, err)
	})
}

2021-09-12 11:30 UTC, cskd8 requested changes
どんなに頑張ってもテストで検証できないコードは出てくるので、テストできる部分は全部カバーできたと思える量のテストを書いてもらえれば十分です。クライアントからの要求のいろいろな状況を想定してそれを再現するようなテストを書けるようになると:clap:って感じです

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl.go
> +	}
```suggestion
	gotGroup, err := repo.client.Group.
		Query().
		Where(group.IDEQ(groupID)).
		First(ctx)
	if err != nil {
		return nil, err
	}
	if gotGroup == nil {
		return nil, errors.New("unknown group id")
	}

	members, err := gotGroup.
		QueryUser().
		All(ctx)
	if err != nil {
		return nil, err
	}
```

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl.go
> +		SetName("group").
この`SetName`ってどういう目的でつけていますか？名前が`group`に変わっちゃうのでやばいと思います

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl.go
> +		SetName("group").
上と同じでいらなそう

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl_test.go
> +	t.Run("Success1", func(t *testing.T) {
他のテストと統一したいので`Success`で大丈夫です

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl_test.go
> +		require.Equal(t, member2.ID, user2.ID)
まあほかのテストがカバーしててそうなるはずなので別になくていいかな～って感じ

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl_test.go
> +	})
`UnknownUser`も作ってあげるとよりよさそう:thumbsup:

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl_test.go
> +	})
`UnknownUser`作ってあげよう:thumbsup:

2021-09-12 11:30 UTC, cskd8 commented on model/group_impl_test.go
> +		require.Equal(t, member.ID, user.ID)
上と同じで、そこまで確認しなくて良さそう

2021-09-13 07:16 UTC, cskd8 requested changes
modelのテスト書くのも良く実装できています LGTM:clap:
traQでも言ったように、routerのテストを追加したいので、traQで言ったやつをやってみてください！

2021-09-20 08:27 UTC, cskd8 requested changes
めちゃいい感じにかけてて:tensai::god:
少し変更してほしい点を書いたので修正お願いします:pray:

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +			DeletedAt:   &date,
`DeletedAt`はまだ消されていないUserなので入れなくて大丈夫です
```go
		user := &model.User{
			ID:          uuid.New(),
			Name:        random.AlphaNumeric(t, 20),
			DisplayName: random.AlphaNumeric(t, 50),
			Admin:       true,
			CreatedAt:   date,
			UpdatedAt:   date,
	        }
```
って感じ
以下の全部のDeletedAtも同じ感じで

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +		unkonwnGroupID := uuid.New()
->`unknownGroupID`
VSCodeのSpellCheckerみたいな拡張機能入れるとTYPOが分かりやすいかも

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +	t.Run("UnkonwnUserID", func(t *testing.T) {
->`UnknownUserID`

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +	t.Run("UnkonwnGroupID", func(t *testing.T) {
->`UnknownGroupID`

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +		unkonwnUserID := uuid.New()
->`unknownUserID`

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +			Return(errors.New("unkown member id"))
-> `unknown`

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +			Return(errors.New("unkown group id"))
->`unknown`

2021-09-20 08:27 UTC, cskd8 commented on router/group_test.go
> +			Return(&model.Member{user.ID}, nil)
```go
&model.Member{
        ID: user.ID,
}, nil
```
このようにフィールド名をちゃんとつける書き方のほうがパッと見でどのフィールドを埋めているのかわかりやすいので、読みやすさの面ではそのようにしてもらったほうが:yosa:です

2021-09-20 09:14 UTC, cskd8 requested changes
1つだけみのがしていた部分があったので対応お願いします:pray:

2021-09-20 09:14 UTC, cskd8 commented on router/group_test.go
> +			Return(&model.Member{ID: user.ID}, nil)
めっちゃ本質から外れているのですが、structってぱってわかるように{のあとと}の前は改行してあげてさっきのレビューの感じでやってあげるとより分かりやすいと思います:+1:

2021-09-20 09:14 UTC, cskd8 commented on router/group_test.go
> +		require.Equal(t, http.StatusOK, statusCode)
ここでPOSTをする必要はなくて、`CreateMember`(だっけ？)を呼んでメンバーを直接作っちゃって構いません(ほかのテストで`CreateMember`はテストできているはずなので)

2021-09-20 09:14 UTC, cskd8 commented on router/group_test.go
> +		require.Equal(t, http.StatusOK, statusCode)
↑と同じ

2021-09-20 09:14 UTC, cskd8 commented on router/group_test.go
> +		require.Equal(t, http.StatusOK, statusCode)
↑と同じ

2021-09-20 13:29 UTC, cskd8 requested changes
temmaくんと話してここだけ修正してもらいたいです:pray:

2021-09-20 13:29 UTC, cskd8 commented on router/group.go
> +	}
```suggestion
	if err != nil {
		if ent.IsConstraintError(err) {
			return badRequest(err)
		}
		return internalServerError(err)
	}
```
そのUUIDを持つUser/Groupが存在しないときは`InternalServerError`よりも`BadRequest`を返したいので、このように`ent`の`IsConstraintError`を利用して`BadRequest`を返すように修正してもらいたいです。
合わせてテストも変更するかも？見てないけど必要あったら修正しておいてもらえると:pray:

2021-09-20 13:29 UTC, cskd8 commented on router/group.go
> +	}
```suggestion
	if err != nil {
		if ent.IsNotFound(err) {
			return notFound(err)
		}
		return internalServerError(err)
	}
```

2021-09-20 13:29 UTC, cskd8 commented on router/group.go
> +	}
```suggestion
	if err != nil {
		if ent.IsNotFound(err) {
			return notFound(err)
		}
		return internalServerError(err)
	}
```

2021-09-23 11:57 UTC, cskd8 approved these changes
LGTM
マージしておきます

2021-09-23 12:04 UTC, merged