Codecovを導入
traPtitech/Jomon pull request #445
Opened 2021-06-24 00:56 UTC by cskd8

できてるのかは知らず...

2021-06-30 14:17 UTC, FujishigeTemma requested changes
どうせ開発環境立ってるところでテスト動かすと思うから`server-test.yml`消して、直接実行するようにしていいと思う。
あと、`[![codecov](https://codecov.io/gh/traPtitech/traQ/branch/master/graph/badge.svg)](https://codecov.io/gh/traPtitech/traQ)`みたいにバッジをつけると嬉しくなれる

2021-06-30 14:17 UTC, FujishigeTemma commented on .github/workflows/go.yml
> +      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
`-race`特に理由ないならつけといて欲しい:pray:

2021-06-30 14:17 UTC, FujishigeTemma commented on .github/workflows/go.yml
> +      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
lintは`go vet`に任せて`golangci-lint`は使わない方向で行く？

2021-06-30 15:52 UTC, cskd8 commented
> どうせ開発環境立ってるところでテスト動かすと思うから`server-test.yml`消して、直接実行するようにしていいと思う。
> あと、`[![codecov](https://codecov.io/gh/traPtitech/traQ/branch/master/graph/badge.svg)](https://codecov.io/gh/traPtitech/traQ)`みたいにバッジをつけると嬉しくなれる

直接実行が曖昧なんだけど、`make up`してから`go test`を手でやればいいって感じ？

2021-07-01 15:19 UTC, FujishigeTemma commented on .github/workflows/go.yml
> +      run: go vet ./...
`go test`のときに自動で走るから書かなくてもOK [ref](https://golang.org/pkg/cmd/go/internal/test/#:~:text=the%20test%20succeeds.-,-vet%20list,-Configure%20the%20invocation)

2021-07-01 15:20 UTC, FujishigeTemma commented
> 直接実行が曖昧なんだけど、make upしてからgo testを手でやればいいって感じ？

そのつもりだった:pray:

2021-07-01 15:26 UTC, cskd8 commented
> > 直接実行が曖昧なんだけど、make upしてからgo testを手でやればいいって感じ？
> 
> そのつもりだった🙏

`make up`とかで手元で試しながらTestするとTest用のデータと試してるデータが混在してめんどくさくない？あとDBへの接続がややめんどくさい

2021-07-01 15:41 UTC, FujishigeTemma commented
DBへの接続は`DB_HOST=localhost go test`とかにすればたぶん良くて、テスト用のデータと混ざるのが嫌なら別でDB建てるようにしたほうが良さそう。いちいち`docker-compose up`のは遅くて辛いと思う。

2021-07-02 06:17 UTC, cskd8 commented
別のDB立ててそっちつかうようにした
そっちも確認用にphpmyadminでアクセスできるようにもしておいた
あとCodeCovはいった✨

2021-07-02 06:43 UTC, FujishigeTemma approved these changes

2021-07-02 06:43 UTC, merged