Group/Owner周りの実装
traPtitech/Jomon pull request #456
Opened 2021-07-01 06:58 UTC by nambatsu

一通り実装できましたのでPR出します。

2021-07-01 07:10 UTC, nambatsu commented
#421

2021-07-01 07:11 UTC, cskd8 commented
close #421
とつけるとマージされた際に自動でcloseされます:)

2021-07-01 15:01 UTC, cskd8 requested changes
レビューの中で、めちゃくちゃ仕様のガバを見つけてしまったので、申し訳ないですが、レビューにあるような仕様の変更にも対応してもらいたいです......
model/group_impl.goは完璧にかけているので、命名に関してと仕様変更に関しての修正をお願いします。実装や仕様に関してなど、わからないことがあったらどんどん質問してください:thumbsup:

2021-07-01 17:36 UTC, nambatsu commented
一通り直してみました

2021-07-02 07:19 UTC, cskd8 requested changes
だいたいいい感じです！インデントの修正などの細かい修正をいくつか挙げていますが、おおよそOKです！
これができたらテストの追加もしたいのですが、Groupを追加等するメソッドができないとできないので、いったんマージしてからあとでまたタスクとしてお願いするかもしれません

2021-07-02 07:19 UTC, cskd8 commented on docs/swagger.yaml
> -          $ref: "#/components/responses/404"
404は残しておいてほしいです

2021-07-02 07:19 UTC, cskd8 commented on docs/swagger.yaml
> +                          $ref: "#/components/schemas/TrapID"
インデントがひとつ深いので直してもらいたいです

2021-07-02 07:19 UTC, cskd8 commented on model/group.go
> +	GetOwner(ctx context.Context, GroupID uuid.UUID) ([]*Owner, error)
ここはOwnerの配列(複数のOwner)が返ってくるので、複数形にしてほしいです:pray:

2021-07-02 07:19 UTC, cskd8 commented on model/group.go
> +	Owner uuid.UUID
uuid.UUIDの名前がOwnerではなく、OwnerのIDがuuid.UUIDなので、フィールド名は`ID`とかのほうがわかりやすいかもしれません。もしなにか理由があるならそのままでも大丈夫です。

2021-07-02 07:19 UTC, cskd8 commented on model/group_impl.go
> +func (repo *EntRepository) GetOwner(ctx context.Context, GroupID uuid.UUID) ([]*Owner, error) {
複数形への変更に伴って変更

2021-07-02 08:10 UTC, nambatsu commented
修正しました

2021-07-03 06:44 UTC, cskd8 requested changes
ひとつだけ細かいところの修正をお願いします！これ以外は完璧なので、修正ができたらマージしたいと思います！！

2021-07-03 06:44 UTC, cskd8 commented on docs/swagger.yaml
> +                        $ref: "#/components/schemas/TrapID"
`owners`の中に`id`を入れずに、直接`id`だけを返してしまって大丈夫です。具体的には以下のようになると思います
```yaml
      responses:
        "200":
          description: 追加に成功した。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: "#/components/schemas/TrapID"
```

2021-07-05 13:43 UTC, cskd8 requested changes

2021-07-05 13:43 UTC, cskd8 commented on model/group_impl.go
> +func (repo *EntRepository) CreateOwner(ctx context.Context, GroupID uuid.UUID, OwnerID uuid.UUID) (*Owner, error) {
ずっと見逃してて今気づいたのですが、引数の変数もcamelCaseにしてほしいです:pray:
他の部分も同様に変更お願いします

2021-07-07 05:55 UTC, nambatsu commented
遅くなりましたが修正しました

2021-07-07 06:27 UTC, cskd8 requested changes

2021-07-07 06:27 UTC, cskd8 commented on model/group_impl.go
> +		All(ctx)
申し訳ないのですが追加でひとつ
```suggestion
	groupowners, err := repo.client.Group.
		Query().
		Where(group.IDEQ(groupID)).
		QueryOwner().
		Select(user.FieldID).
		All(ctx)
```
のようにしてIDだけ取ってくれば十分なので、この追加をお願いします:pray:

2021-07-17 17:24 UTC, nambatsu commented
非常に遅くなりました、直してみました

2021-07-22 14:55 UTC, cskd8 reviewed
LGTM:thumbsup:
ここからさらにownersに関するテストを追加してほしいです。
まずは今のv2をrebaseしてほしいです:pray:
```sh
git checkout v2
git pull
git checkout group-members
git pull
git rebase v2
```
これでできるはずです

テストは、`model/tag_impl_test.go`を見るとなんとなく雰囲気がわかると思うんですけど、それぞれのメソッドに関して望まれた挙動をしているか確認するものです。手を付け始めるとわかると思うんですけど、CreateUserがないとTest用のユーザーを用意するのが大変なので、traQに引用を貼る`user.go`、`user_impl.go`を`model/user.go`、`model/user_impl.go`と差し替えて使ってください:thumbsup:

2022-01-03 08:51 UTC, cskd8 commented
@cskd8 がやります

2022-01-03 10:02 UTC, cskd8 approved these changes

2022-01-03 10:02 UTC, merged