request_status周りの実装
traPtitech/Jomon pull request #531
Opened 2022-02-19 05:15 UTC by shota-aa

2022-02-20 08:03 UTC, cskd8 reviewed
見た感じいい感じの実装ができてそう、schema変えるPRのやつとごっちゃになって少し読みづらいので、今のv2にrebaseしてくれると助かる
とりあえず意図の確認を1つだけ

2022-02-20 08:03 UTC, cskd8 commented on model/request_impl.go
> +func convertEntRequestResponseToModelRequestResponse(request *ent.Request, tags []*ent.Tag, group *ent.Group, status *ent.RequestStatus, user *ent.User) *RequestResponse {
これってなにか意図ありますか？

2022-02-20 08:09 UTC, shota-aa commented on model/request_impl.go
> +func convertEntRequestResponseToModelRequestResponse(request *ent.Request, tags []*ent.Tag, group *ent.Group, status *ent.RequestStatus, user *ent.User) *RequestResponse {
routerで使わなそうなので、model層でしか使いませんというのが分かりやすいと思って小文字にしました

2022-02-20 08:18 UTC, shota-aa commented
Current branch request-status is up to date.
とでるだけで、rebaseで見やすくするというのは多分できなさそうです:pray:

2022-02-21 09:34 UTC, cskd8 commented
こういう感じにならないですか？
![image](https://user-images.githubusercontent.com/57042565/154927603-c82bcbe5-d50e-4977-8300-59799787b3a9.png)

2022-02-21 09:37 UTC, cskd8 commented on model/request_impl.go
> +func convertEntRequestResponseToModelRequestResponse(request *ent.Request, tags []*ent.Tag, group *ent.Group, status *ent.RequestStatus, user *ent.User) *RequestResponse {
あ～了解です。それなら`ConvertEntGroupToModelGroup`とかも別のPRでlowerにしといたほうが良さそうですね

2022-02-21 11:18 UTC, shota-aa commented
うまくできませんでした。
![image](https://user-images.githubusercontent.com/83848816/154945209-c34d1d7c-8a69-42e9-9f90-422a6ee80df8.png)

2022-02-21 11:23 UTC, shota-aa commented
model/request_impl.go, request_status.go, request_target.go, request_impl_test.go(createStatusのテストのところのみ) router/router_test.go
あたりをみてほしいです。

2022-02-21 11:27 UTC, shota-aa commented
modelrequest_impl.goの
(repo *Entrepository) UpdateRequest
はこのブランチで修正しています。これら以外は別ブランチの修正です。
お願いします:pray:

2022-02-22 08:14 UTC, cskd8 commented
rebaseしたあとはforce pushしないでpullするとマージになっちゃうので、force pushしてください。
一応変更点は見ておきます

2022-02-22 08:42 UTC, cskd8 requested changes
差分の見逃しでレビューできていないところもあるかもしれませんが、気が付いたところをレビューしておきました

2022-02-22 08:42 UTC, cskd8 commented on model/request_impl.go
>  	}
L270のコメントに関することですが、`group`がnilで`entgroup`がnilじゃない場合にnilにするようにしてくれると助かる

2022-02-22 08:42 UTC, cskd8 commented on model/request_impl.go
> +}
`request_target.go`に移動

2022-02-22 08:42 UTC, cskd8 commented on model/request_impl.go
> +
`request_status.go`に移動

2022-02-22 08:42 UTC, cskd8 commented on model/request_impl.go
> +}
正しい場所に移動

2022-02-22 08:42 UTC, cskd8 commented on model/request_impl_test.go
> +}
`Success`だけではテストとしてやばいのでいろいろなケースを追加してください

2022-02-22 08:42 UTC, cskd8 commented on model/request_status.go
> +//multipart/form-dataじゃないから使わなそう
意図がわからなかった、消しても動作したということですか？

2022-02-22 08:42 UTC, cskd8 commented on model/request_status.go
> +}
内部で状態を文字列として持つのは避けてください

2022-02-22 08:42 UTC, cskd8 commented on router/request.go
> +	Status    string    `json:"status"`
状態はStatusで持ってください

2022-02-23 15:09 UTC, shota-aa commented on model/request_status.go
> +//multipart/form-dataじゃないから使わなそう
自分がこれを使わず、c.Bind()を使って実装してしまったので、消しても動作しました。

2022-02-23 15:25 UTC, shota-aa commented on model/request_status.go
> +//multipart/form-dataじゃないから使わなそう
あ、今意図を理解しました。goの仕様を理解してなかったです。

2022-02-24 11:58 UTC, shota-aa commented on model/request_status.go
> +}
bindする時はStatusで状態をもつように修正しました。
DBにstringで入っているので、一部はこの関数を使わざるをえない感じになってます。

2022-02-24 12:03 UTC, shota-aa commented
PostCommetもそうですが、テストでsessionからユーザーを取ってくる必要がある、つまりテストにtraQのoauthが必要なので、どういう感じにテストを書こうかとなっています。

2022-02-24 12:54 UTC, cskd8 requested changes
`go generate ./...`を叩いてなさそう？実行してそれもcommitしてください
あとrouterのrequest_testにAPIのテスト欲しいですね、model周りが終わったら追加してくれると助かります

2022-02-24 12:54 UTC, cskd8 commented on model/request_status.go
> +}
実装は`request_status_impl.go`にして、interfaceを`request_status.go`に書いてほしいです(ほかのモデル層と同じ感じで)
何度ももうしわけないです

2022-02-24 12:54 UTC, cskd8 commented on model/request_status.go
> +}
entの`Status`とmodelの`Status`をConvertする関数を書くといいと思います。

2022-03-05 12:38 UTC, cskd8 requested changes
いい感じだと思います！細かいところを少しだけ

2022-03-05 12:38 UTC, cskd8 commented on router/request.go
> +	if u.Admin {
ここって`user.Admin`じゃだめですか？なんかセキュリティ的にやばいんだっけ

2022-03-05 12:38 UTC, cskd8 commented on router/request.go
> +	// create status and comment
順番が大切なことをコメントで書いておいてもらえるとありがたい

2022-03-05 12:38 UTC, cskd8 commented on router/request.go
> +	return true
```suggestion
	if status == model.FixRequired && latestStatus == model.Submitted ||
	   status == model.Rejected && latestStatus == model.Submitted ||
	   status == model.Submitted && latestStatus == model.Accepted {
		return false
	}
	return true
```

昔俺が書いたコードだけど、こういうほうが分かりやすいかも？

2022-03-05 12:38 UTC, cskd8 commented on router/request_test.go
> +			Status:    model.Status(1),
```suggestion
			Status:    model.Submitted,
```

他も同様

2022-03-05 13:25 UTC, shota-aa commented on router/request.go
> +	if u.Admin {
シンプルにuser.Adminでadminか分かることを忘れていました。ただ、admin情報を変えたときに、そのユーザーがsessionを一回破棄しなくてもいいくらいのメリットはあると思われます。。。？
セキュリティ面はこれがやばかったら色々やばいということになると思うので大丈夫なんじゃないですかね。

2022-03-05 13:26 UTC, shota-aa commented on router/request.go
> +	if u.Admin {
つまりセキュリティ的のことは考えてなかったです。

2022-03-05 14:53 UTC, shota-aa commented
https://github.com/traPtitech/Jomon/pull/531/commits/ee30af1914b60ce1434b87a4910aa4f5a5a76385
のテストが落ちたのは、おそらくTestEntRepository_GetUsersの中でDBのデータが残ってしまっていたからだと思います。試しに、time.sleep(milisecond)をlen(got)==0の方のテストに書くと確実に落ちるようになりました。並行処理とはいえ順番を変えれば若干開始時刻がずれていい感じになると思うので順番を変えました。

2022-03-06 09:40 UTC, cskd8 commented on router/request.go
> +	if u.Admin {
AdminになったときにはDBの書き込み後にsessionも書き換えしてあげれば親切ですね、実装したほうが良さそう
いずれにせよこのメソッドの責務ではないのでDBを見るだけにしてください。

2022-03-06 09:50 UTC, cskd8 commented
> time.sleep(milisecond)をlen(got)==0の方のテストに書くと確実に落ちるようになりました。

ここが手元で再現性ないのでコード貼って
ほしいです

2022-03-06 10:16 UTC, shota-aa commented
> > time.sleep(milisecond)をlen(got)==0の方のテストに書くと確実に落ちるようになりました。
> 
> ここが手元で再現性ないのでコード貼ってほしいです

```
t.Run("Success", func(t *testing.T) {
		t.Parallel()
                time.Sleep(time.Millisecond)
		ctx := context.Background()

		got, err := repo.GetUsers(ctx)
		assert.NoError(t, err)
		assert.Len(t, got, 0)
	})
```
という感じです

2022-03-06 10:53 UTC, cskd8 commented
これ、テストのDBの問題で前も解決しようとした問題なのでちょっと解決を試みてみます
具体的にはv1のときにはそれぞれのテスト後にDBのデータが消されていたのが出来ていないという問題で、これが出来ればテスト落ちたのも解決すると思います

2022-03-06 12:35 UTC, shota-aa commented on router/request.go
> +	if u.Admin {
とりあえずこのままにしておきますね。
あと特定のsessioinの中身を変えるのってできるんですかね。できなければsessionでadminを判断することがないようにするのが良さそうな気がします。

2022-03-06 19:02 UTC, cskd8 commented
とりあえずマージして、この問題はissueとして別ブランチで考えてみます:thumbsup:

2022-03-06 19:03 UTC, cskd8 commented on router/request.go
> +	if u.Admin {
あ、ごめんなさい、これDBを見るだけって言っちゃってるけどsessionを見るだけの間違いです

2022-03-06 19:07 UTC, cskd8 approved these changes

2022-03-06 19:07 UTC, merged