request_target周りの実装
traPtitech/Jomon pull request #541
Opened 2022-03-09 08:27 UTC by shota-aa

2022-03-09 08:35 UTC, cskd8 commented
schema.mdはもう使ってないので編集しなくても大丈夫です(かわりにentが生成してる(正式にはenterが生成してる)er.htmlを使ってる)

2022-03-16 10:19 UTC, shota-aa commented
requestテーブルにamountを入れる必要はない。
合計して計算して返せばよさそう。

2022-03-17 13:50 UTC, cskd8 requested changes
基本的に良さそう
数個Request changesって感じなのでお願いします:pray:

2022-03-19 12:19 UTC, shota-aa commented on ent/schema/requesttarget.go
> -			Required(),
修正しました。

2022-04-16 06:10 UTC, shota-aa commented
たぶんあとtest書くだけだった気がする

2022-04-16 14:59 UTC, cskd8 commented
コンフリクトやばすぎて解消できないから別ブランチで俺がやります

2022-04-16 20:03 UTC, FujishigeTemma commented
:w:

2022-04-17 14:22 UTC, cskd8 commented
#570 に移行

2022-04-17 14:23 UTC, closed without merging