DELETE owner/memberのrequestBodyを削除
traPtitech/Jomon pull request #550
Opened 2022-03-20 08:29 UTC by cskd8

Query Paramに変更

2022-04-02 13:23 UTC, shota-aa requested changes

2022-04-02 13:23 UTC, shota-aa commented on router/group_test.go
>  	t.Run("NilUUID", func(t *testing.T) {
NilGroupUUIDがいいと思います。

2022-04-02 13:23 UTC, shota-aa commented on router/group_test.go
>  	t.Run("InvalidUUID", func(t *testing.T) {
InvalidGroupUUIDと同じなので消していいと思います。

2022-04-02 13:23 UTC, shota-aa commented on router/group_test.go
>  	t.Run("NilUUID", func(t *testing.T) {
NilGroupUUIDがいいと思います。

2022-04-02 13:23 UTC, shota-aa commented on router/group_test.go
>  	t.Run("InvalidUUID", func(t *testing.T) {
InvalidGroupUUIDと同じなので消していいと思います。

2022-04-03 07:52 UTC, cskd8 commented on router/group_test.go
>  	t.Run("NilUUID", func(t *testing.T) {
![image](https://user-images.githubusercontent.com/57042565/161417292-5dac1f27-1b4a-4528-9b0f-f20800e3b37c.png)
ほかのテストでもこの名前でやってるから統一させてたけど、他のも変更したほうがいいですか？

2022-04-03 07:54 UTC, cskd8 commented on router/group_test.go
>  	t.Run("InvalidUUID", func(t *testing.T) {
`InvalidGroupUUID`ってどれのこと？
もし`UnknownGroupID`のことなら`InvalidUUID`はUUIDのパースエラー、`UnknownGroupID`はGroupがnot foundになるエラーで異なる異常系をテストしています

2022-04-04 12:57 UTC, shota-aa approved these changes

2022-04-04 13:04 UTC, merged