Groupを実装
traPtitech/Jomon pull request #553
Opened 2022-03-22 17:04 UTC by cskd8

PostGroupとか忘れてた

2022-04-05 09:26 UTC, FujishigeTemma requested changes

2022-04-05 09:26 UTC, FujishigeTemma commented on router/group.go
>  func (h *Handlers) PostGroup(c echo.Context) error {
↓みたいな感じでコメントを残しておいてくれるとわかりやすくて嬉しい
```suggestion
// PostGroup POST /groups
func (h *Handlers) PostGroup(c echo.Context) error {
```

2022-04-05 09:26 UTC, FujishigeTemma commented on router/group.go
> +		c.Logger().Error(err)
これ書かなくてもログに吐かれてる。
https://echo.labstack.com/middleware/logger/
実装はecho.goのDefaultHTTPErrorHandlerがServeHTTPから呼ばれてるからそこを見ればいいと思う。

2022-04-05 09:26 UTC, FujishigeTemma commented on model/group_impl.go
> +		SetBudget(*budget).
これ`budget`が指定されてないjsonが飛んでくると、nilが渡ってきてnil pointer dereferenceでpanicするからSetNillableBudget使ったほうが良さ。

2022-04-05 09:29 UTC, FujishigeTemma commented
テストの内容まではまだ見れてないんだけど、一応optionalなJSON fieldのチェックとは書いたほうが良さそう。
それと、CreateOwnerとCreateMemberはリソースの作成はしてなくて、紐付けをしてるだけだからAdd~のほうが正しい気がする。

2022-04-05 13:51 UTC, cskd8 commented
> テストの内容まではまだ見れてないんだけど、一応optionalなJSON fieldのチェックとは書いたほうが良さそう。

チェックってどういうの？

2022-04-06 15:05 UTC, FujishigeTemma commented
optionalなfieldを含まない場合のJSONをテストケースに含むってこと。それをしてたら、レビューで指摘したとことかは判明してそうだなって思ってた。

2022-04-10 09:59 UTC, FujishigeTemma approved these changes
:LGTM:

2022-04-10 10:00 UTC, merged

2022-04-10 10:00 UTC, FujishigeTemma commented
いや、待って。Swaggerの変更反映してるか見てないわ。先にマージしてもいいけど。

2022-04-10 10:01 UTC, cskd8 commented
おーーーい:w:
見てなにかあったらここにコメント頼む

2022-04-10 10:02 UTC, FujishigeTemma commented
ごめんち。後で見ますん。