Adminを実装
traPtitech/Jomon pull request #564
Opened 2022-04-04 13:23 UTC by cskd8

2022-04-11 13:48 UTC, cskd8 commented
middlewareがちゃんと書けてるかわからん

2022-04-12 19:43 UTC, FujishigeTemma requested changes

2022-04-12 19:43 UTC, FujishigeTemma commented on router/admin.go
> +	admins, err := h.Repository.GetAdmins(ctx)
`c.Response().Context()`にコンテキストがあるから使うと良さそう

2022-04-12 19:43 UTC, FujishigeTemma commented on router/admin.go
> +}
使ってなさそう

2022-04-12 19:43 UTC, FujishigeTemma commented on router/middleware.go
> +			c.Logger().Error(err)
これどっかで前書いたけど消していいやつ

2022-04-12 19:43 UTC, FujishigeTemma commented on router/middleware.go
> +		gob.Register(&User{})
これが何で書かれてるかわからんかった

2022-04-12 19:43 UTC, FujishigeTemma commented on router/middleware.go
> +		}
これ前段階で担保されてるだろうからgetUserInfoとかで切り出してパニックするなりエラー返すなりして良いような気もする

2022-04-12 19:43 UTC, FujishigeTemma commented on router/middleware.go
> +		sess, err := h.SessionStore.Get(c.Request(), h.SessionName)
gorilla/sessionsが露出してるの多分おかしくて、`session.Get`を使うべき。Handler構造体にSessionStore入れてるのがそもそも間違ってそう。
```suggestion
		sess, err := session.Get(c, sessionName)

```

2022-04-12 19:43 UTC, FujishigeTemma commented on router/middleware.go
> +func (h Handlers) RetrieveGroupOwner(repo model.Repository) echo.MiddlewareFunc {
midlewareでDBアクセスあるのどうなんかなと言う気持ち...わからん
個人的にはかなり微妙な気がしていて、handlerで確認するほうが良いかなって思ってる

2022-04-19 18:17 UTC, FujishigeTemma approved these changes
だいたい良さそう

2022-04-19 18:17 UTC, FujishigeTemma commented on router/middleware.go
> +			owners, err := repo.GetOwners(ctx, id)
いつもの

2022-04-19 18:17 UTC, FujishigeTemma commented on router/middleware.go
> +			request, err := repo.GetRequest(ctx, id)
これも

2022-04-19 18:17 UTC, FujishigeTemma commented on router/router.go
> +	e.Use(session.Middleware(sessions.NewCookieStore([]byte(h.SessionName))))
ここはセッション名ではなくて隠したほうが良いやつ
https://github.com/gorilla/sessions

2022-06-25 13:23 UTC, FujishigeTemma commented
多分マージできたはず

2022-06-27 09:15 UTC, cskd8 commented
確認してマージする

2022-06-29 14:21 UTC, merged