Transactionに関するWebhookの実装
traPtitech/Jomon pull request #626
Opened 2022-11-10 08:01 UTC by karo1111111

transactionがなされたときに#services/Jomonにチャンネルに通知が流れるようにする。
(:@chebrinko:さんの書いたもの)

2022-11-10 08:20 UTC, cskd8 commented
close #598

2022-11-11 01:30 UTC, mehm8128 reviewed
どんな感じの見た目になるか、traQに実際に入力してMDプレビューで確認してみるといいと思います(もしくは自分宛のDMで実際に送信してみたりして)

あとrequestの日本語訳、「依頼」ではなくて「申請」の方がいい気がしました(今回のissueの範囲外ですが)

@cskd8 軽く見てみて気になったところ指摘してみましたが、間違っているところや追加で指摘事項などあれば書いておいてください🙏

2022-11-11 01:30 UTC, mehm8128 commented on service/webhook.go
> +		}
requestに合わせて「トランザクション」の前にスタンプを入れたいです(良さげなスタンプ探してみてください、なければ作ることになりそう)

2022-11-11 01:30 UTC, mehm8128 commented on service/webhook.go
> +
requestと同様に、URLを入れたいです
ただ、requestと違ってタイトルがないのでリンクの文字をどうするか考える必要がありそうです(もしくは上の「トランザクション」の文字をリンクにしてもいいかも)

2022-11-11 01:30 UTC, mehm8128 commented on service/webhook.go
> +		}
transationは「traPから支払ったもの」と「traPに振り込まれたもの」があるので、金額の符号(どっちがどっちかはwikiに書いてあったはず)で場合分けして「支払」、「請求先」みたいなのを工夫してほしいです

2022-11-11 01:30 UTC, mehm8128 commented on service/webhook.go
> +
[swagger](https://apis.trap.jp/?urls.primaryName=Jomon%20v2%20API#/Transactions/getTransactions)でいう`target`に当たるものも追加したいです

2022-11-11 02:22 UTC, mehm8128 commented
requestの方もtargetがなかったり依頼→申請にしたかったり請求先グループっていう表現が怪しかったり、修正したいところいくつかある気がするのでそっちも別でissue&PR立てた方がよさそうです

2022-11-11 06:10 UTC, karo1111111 commented
> traQに実際に入力してMDプレビューで確認してみるといいと思います(もしくは自分宛のDMで実際に送信してみたりして)

すみません、詳しいやり方(あるいはそれが書かれたwikiなどあれば)教えていただけますか?traQのどこに入力すれば良いかなどがわからないです

2022-11-11 06:12 UTC, mehm8128 commented
![image](https://user-images.githubusercontent.com/83744975/201275166-43f16e20-7bf9-42f6-922f-617c7857fb2e.png)
大した話ではなくて、表示しようとしているメッセージ(`## トランザクションが作成されました`、など)を普通にメッセージ投稿するみたいにここに入れて左のMDボタンクリックしてプレビュー確認してみればって話です(ユーザーじゃなくてwebhookが投稿するってだけで、実質ただのtraQへの投稿なので)

> > traQに実際に入力してMDプレビューで確認してみるといいと思います(もしくは自分宛のDMで実際に送信してみたりして)
> 
> すみません、詳しいやり方(あるいはそれが書かれたwikiなどあれば)教えていただけますか?traQのどこに入力すれば良いかなどがわからないです

2022-11-11 06:14 UTC, karo1111111 commented
> ![image](https://user-images.githubusercontent.com/83744975/201275166-43f16e20-7bf9-42f6-922f-617c7857fb2e.png) 大した話ではなくて、表示しようとしているメッセージ(`## トランザクションが作成されました`、など)を普通にメッセージ投稿するみたいにここに入れて左のMDボタンクリックしてプレビュー確認してみればって話です(ユーザーじゃなくてwebhookが投稿するってだけで、実質ただのtraQへの投稿なので)
> 
> > > traQに実際に入力してMDプレビューで確認してみるといいと思います(もしくは自分宛のDMで実際に送信してみたりして)
> > 
> > 
> > すみません、詳しいやり方(あるいはそれが書かれたwikiなどあれば)教えていただけますか?traQのどこに入力すれば良いかなどがわからないです

なるほど。ありがとうございます

2022-11-14 07:34 UTC, mehm8128 reviewed
複数箇所似たような修正点がある場合でも1回だけ指摘したので、自分で他にも同じような箇所がないか確認してみてください🖖

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +
ここ括弧閉じ消えちゃってるので、最後にバグ直したときに別のところで閉じちゃったっぽいですね(124行目に入っちゃってそうです)

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("[入出金記録](%s/applications/%s)", "https://jomon.trap.jp", resApp.ID) + "が新規作成されました" + "\n"
1行にまとめられそうです
```suggestion
			message += fmt.Sprintf("## :scroll:[入出金記録](%s/applications/%s)が新規作成されました\n", "https://jomon.trap.jp", resApp.ID)
```

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("[入出金記録](%s/applications/%s)", "https://jomon.trap.jp", resApp.ID) + "が新規作成されました" + "\n"
URL、`%s/applications/%s`だとv1の申請のURLなので、`%s/transactions/%s`にしてほしいです

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message = message[:len(message)-len(", ")]
これいらなさそうです(元々最後のカンマを消すために使われてたぽいけど`strings.Join`使ったら必要ないので)

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message += strings.Join(tags, ",")
```suggestion
			message += fmt.Sprintf("- タグ: %s", strings.Join(tags, ","))
```
みたいにしたら151行目の処理をまとめられそうです

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("- 支払い金額: % -s円", strconv.Itoa(resApp.Amount)) + "\n"
この表記、マイナス符号を消してくれるんですかね(詳しくないので分からず)
単純に`strconv.Itoa(-resApp.Amount)`とかでどうですか

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("- %s", resApp.Target) + "への依頼" + "\n"
```suggestion
				message += fmt.Sprintf("- %sへの支払い\n", resApp.Target)
```
これでどうですか

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			if resApp.Group != nil {
GroupじゃなくてTargetですかね

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +		message += fmt.Sprintf("- 関連するグループ: %s", resApp.Group.Name) + "\n"
groupがない場合もあるので他のところと同様に条件分岐してほしいです

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			if resApp.Group != nil {
というかtargetは絶対に入っているので、条件分岐しなくて大丈夫そうです

2022-11-14 07:34 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("[入出金記録](%s/applications/%s)", "https://jomon.trap.jp", resApp.ID) + "が新規作成されました" + "\n"
これみたいに、改行コードだけ別の文字列になってて足してるだけ、みたいなところ何か所かあるので同様に修正してみてください

2022-11-14 07:36 UTC, mehm8128 commented on service/webhook.go
> +
https://github.com/traPtitech/Jomon/pull/626/files
files changed見ればv2ブランチとの差分が見れるので、必要ないところで差分が生じていないか注意してみてください

2022-11-14 17:16 UTC, karo1111111 commented on service/webhook.go
> +
あ。気がついていませんでした…ありがとうございます…
files changedについては存在を知らなかったのでとても助かります!

2022-11-14 17:17 UTC, karo1111111 commented on service/webhook.go
> +			message += fmt.Sprintf("[入出金記録](%s/applications/%s)", "https://jomon.trap.jp", resApp.ID) + "が新規作成されました" + "\n"
なるほど…１行にまとめられることや改行コードを文末につけられると知りませんでした…とても勉強になります。ありがとうございます!

2022-11-14 17:17 UTC, karo1111111 commented on service/webhook.go
> +			message += fmt.Sprintf("[入出金記録](%s/applications/%s)", "https://jomon.trap.jp", resApp.ID) + "が新規作成されました" + "\n"
ありがとうございます。修正させていただきます。

2022-11-14 17:18 UTC, karo1111111 commented on service/webhook.go
> +			message = message[:len(message)-len(", ")]
strings.Join使うといらないんですね…勘違いをしていました。次からもう少し調べます。ありがとうございます!

2022-11-14 17:18 UTC, karo1111111 commented on service/webhook.go
> +			message += strings.Join(tags, ",")
なるほど!ありがとうございます!

2022-11-14 17:22 UTC, karo1111111 commented on service/webhook.go
> +			message += fmt.Sprintf("- 支払い金額: % -s円", strconv.Itoa(resApp.Amount)) + "\n"
どうやって符号消せばいいかで悩んでいたので助かります(コミットした後でString型に直した状態でこの表記はまずいのでは…?と思い始め、結局どうすれば良いのか悩んでいたのでありがたいです…)
`strconv.Itoa(-resApp.Amount)`として良いとは思っていませんでした…本当にありがとうございます!!

2022-11-14 17:23 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("- %s", resApp.Target) + "への依頼" + "\n"
すみません…完全にミスしていました。files changedで確認するようにします。

2022-11-14 17:24 UTC, karo1111111 commented on service/webhook.go
> +			if resApp.Group != nil {
またミスをしました…すみません…
条件分岐の件についても修正させていただきます!ありがとうございます!

2022-11-14 17:25 UTC, karo1111111 commented on service/webhook.go
> +		message += fmt.Sprintf("- 関連するグループ: %s", resApp.Group.Name) + "\n"
修正させていただきます!ご指摘ありがとうございます!!

2022-11-15 01:44 UTC, mehm8128 reviewed
だいぶよくなってきたのですが、追加で何点か指摘したのでお願いします

2022-11-15 01:44 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("- タグ: %s", strings.Join(tags, ","))
多分今の状態だと
- タグ: aaa,bbb,ccc

みたいになると思うのですが、
- タグ: `aaa` `bbb` `ccc`

みたいにした方が見た目よさそうなのでそうしてほしいです(ikura-hamu botのタグ表示みたいな感じ)

2022-11-15 01:44 UTC, mehm8128 commented on service/webhook.go
> +		}
金額は1つネストされた構造にした方がよさそうです
- aaaへの支払い
  - 支払金額: 100円

みたいに

2022-11-15 01:44 UTC, mehm8128 commented on service/webhook.go
> +		}
あと支払金額が`% s円`になっちゃってるのでスペース消して`%s円`にしてほしい

2022-11-15 01:44 UTC, mehm8128 commented on service/webhook.go
> -
すごい細かいけどここの改行消えちゃってるから戻しておいてほしいかも

2022-11-15 02:45 UTC, mehm8128 reviewed
ちょっと難しいので一番最後にやってほしいやつについてコメントしました

2022-11-15 02:45 UTC, mehm8128 commented on service/webhook.go
> +		}
transactionの作成について、基本は1つずつなんですけど部費振込などで一気に複数の振込が発生した場合に、Targetをその対象全員選択して一気に複数のtransactionを作成することができる仕様になっています。
そして、その場合に全部の通知をtraQに飛ばすとすごいことになってしまうのでそれを1つにまとめたいです。
そのために、`resApps := make([]TransactionReqeustApplication)`みたいにしてスライスを作り、さらに要素の0番目を新しく`resApp`として定義し直して、
- `resApps`の要素数が1なら今まで通りの実装
- `resApps`の要素数が2以上であればTarget以外は`resApp`を使って今まで通りの実装、Targetはタグと同じような感じで`resApps`から複数表示

みたいな実装にしてほしいです

2022-12-08 08:15 UTC, karo1111111 commented on service/webhook.go
> +		}
スライス作る時
```
変数名 := make([]入れる型（Generics的な？）, len(長さ), cap(キャパシティ))
```
だと思っていたのですが、
```
resApps := make([]TransactionReqeustApplication)
```
これってどのように定義しているのでしょうか?

2022-12-08 09:16 UTC, karo1111111 commented on service/webhook.go
> +		}
気づいてくださりありがとうございます。修正させていただきます。

2022-12-08 09:17 UTC, karo1111111 commented on service/webhook.go
> -
了解です。修正させていただきます

2022-12-08 09:17 UTC, karo1111111 commented
コミットしました。レビューよろしくお願いいたします。

2022-12-08 11:46 UTC, karo1111111 commented
コミットしました。今度は正しくできているでしょうか?

2022-12-08 11:50 UTC, mehm8128 commented
できてそうなので見ますねー

2022-12-08 12:28 UTC, mehm8128 reviewed
やってほしいことの言語化が上手くできなくてすごい分かりにくいレビューになってしまっている気がするので、分からなかったらまた聞いて下さい🙏

あとこれ↓が忘れられている気がするのでこれもお願いします
https://github.com/traPtitech/Jomon/pull/627#issuecomment-1312509986

2022-12-08 12:28 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("- タグ: `%s`", strings.Join(tags, ","))
`aaa`,`bbb`,`ccc`という3つのタグがあったとき、`strings.Join(tags, ",")`が`aaa,bbb,ccc`という値になるので、この実装だと`aaa,bbb,ccc`という表示になってしまいます。
なのでこうではなくて、142行目で
```
tags[i] = fmt.Sprintf(`%s`, tag.Name)
```
みたいにして、`fmt.Sprintf`の方は元のままにしておくのがよさそうです
そうするとタグの1つ1つがバッククォートで囲まれていい感じに表示されそう
あとそれをカンマで区切るのではなくてスペースで区切りたいので、`strings.Join(tags, ",")`となっているところは`strings.Join(tags, " ")`にするのがよさそうです
ikura-hamu BOTが多分似たようなことしてる気がするのでGiteaでコード読んでみるといいと思います

2022-12-08 12:28 UTC, mehm8128 commented on service/webhook.go
>  		err := json.Unmarshal(resBody, resApp)
スライス作るときの質問してくれてたのでここで返すと、make使うと確かに長さが必要だったっぽいので書き方はこれでOKです
`json.Unmarshal`で作った配列(resApp)にresBodyを入れたいのですが、
>- resAppsの要素数が1なら今まで通りの実装
>- resAppsの要素数が2以上であればTarget以外はresAppを使って今まで通りの実装、Targetはタグと同じような感じでresAppsから複数表示

といったときの要素数はjson.Unmarshalした後でしか分からないので、
1. varなんたらで配列生成
1. `json.Unmarshal`(VSCodeで見たら黄色い線引かれてたので、`&resApps`としてポインタを渡すようにしないといけなさそう)
1. `resApp`に`resApp`の0番目を割り当て(前は長さが1のときはそのままと言いましたが、使いづらそうなのでどちらの場合でも0番目の値を`resApp`に割り当てるのがよさそうです)

みたいな流れがよさそうです(めちゃくちゃ分かりにくいと思うので分からなかったらもう1回聞いてもらうか、なんとなく実装してみてほしいです🙏)

2022-12-08 12:28 UTC, mehm8128 commented on service/webhook.go
> +				}
`cap`じゃなくて`len`で場合分けしてほしいかな

targetが複数の場合でも支払金額・受取金額は全員同じなので、`%sへの支払い`の%sの部分にタグと同じように配列をstrings.Joinしたtargetたちの文字列を入れるようにしてほしいです

2022-12-09 20:51 UTC, karo1111111 commented on service/webhook.go
> +			message += fmt.Sprintf("- タグ: `%s`", strings.Join(tags, ","))
すみません、読み落としていました…修正します!!

2022-12-09 22:33 UTC, karo1111111 commented on service/webhook.go
> +				}
了解です!レビューありがとうございます!

2022-12-09 22:50 UTC, karo1111111 commented on service/webhook.go
>  		err := json.Unmarshal(resBody, resApp)
質問失礼いたします…3については現状の形(現在の125~126行目)のような形でよろしいでしょうか?

2022-12-10 03:39 UTC, mehm8128 commented on service/webhook.go
>  		err := json.Unmarshal(resBody, resApp)
処理の順番とjson.Unmarshalの書き方をちょっといじるだけで、1と3については現状の書き方で問題なさそうです👌

2022-12-10 03:41 UTC, karo1111111 commented on service/webhook.go
>  		err := json.Unmarshal(resBody, resApp)
了解です!ありがとうございます!

2022-12-10 04:08 UTC, karo1111111 commented
コミットしました。レビューよろしくお願いいたします。

2022-12-10 08:41 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("- `%s`への支払い\n    - 支払い金額: %s円\n", resApp.Target, strconv.Itoa(-resApp.Amount))
`strconv.Itoa`しなくても、%sの代わりに%dにすれば数値を表示できそうです👀

2022-12-10 08:41 UTC, mehm8128 commented on service/webhook.go
> +	Targets []*Targets `json:"targets"`
resAppsが配列として渡ってきて、その中にtargetが1つずつ入っているという構造なので、targetsはいらないですねー

2022-12-10 08:41 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("への支払い\n    - 支払い金額: 計%s円\n,      (一人当たりの支払い金額: 計%s円\n", strconv.Itoa(-len(resApp.Target)*resApp.Amount), strconv.Itoa(-resApp.Amount))
ここらへんも上でレビューした2つを踏まえて修正してみてください

2022-12-10 08:41 UTC, mehm8128 commented on service/webhook.go
> +		resApp := &resApps[0]
想定していたのはこんな感じですね👀
`json.Unmarshal`とか理解するのがちょっと難しいと思うので調べてみてください
```
var resApps []TransactionRequestApplication
err := json.Unmarshal(resBody, &resApps)
(エラーハンドリング)
resApp := resApps[0]
```

2022-12-10 08:41 UTC, mehm8128 commented on service/webhook.go
> +	Targets []*Targets `json:"targets"`
この構造体はswaggerのPOST transactionのレスポンスに対応しているはずなのでそれを見てみるといいです(一部いらないのは抜けていますが)

2022-12-10 08:45 UTC, mehm8128 commented
コミットメッセージについて、多分今は
- 大きいコミットメッセージ(PR名？)
- その詳細(作業内容を箇条書き)
みたいにしてると思うのですが、PR名は不要なので、詳細に箇条書きで書いてあるものをそれぞれ別のコミットにすると分かりやすくなると思います(3つ箇条書きで書くなら3つのコミットに分ける、ということです)

あと今ってもしかしてGithub上でコード書いたりしてコミットしていますか？
CIで作業した方が今後のためにも良いと思うのでそちらの方がおすすめです

2022-12-12 04:13 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("- `%s`への支払い\n    - 支払い金額: %s円\n", resApp.Target, strconv.Itoa(-resApp.Amount))
なるほど、確かにそうですね…ありがとうございます!!

2022-12-12 09:41 UTC, karo1111111 commented on service/webhook.go
> +	Targets []*Targets `json:"targets"`
なるほど…ありがとうございます。
すると、`target := resApps[i].Target`でresApps[i]のtargetが取り出せるという認識で良いのでしょうか?

2022-12-12 09:49 UTC, karo1111111 commented on service/webhook.go
> +	Targets []*Targets `json:"targets"`
了解です1レビューありがとうございます！

2022-12-12 09:50 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("への支払い\n    - 支払い金額: 計%s円\n,      (一人当たりの支払い金額: 計%s円\n", strconv.Itoa(-len(resApp.Target)*resApp.Amount), strconv.Itoa(-resApp.Amount))
了解です!レビューありがとうございます!!

2022-12-12 12:04 UTC, mehm8128 commented on service/webhook.go
> +			}
タグと同じように、配列に保存してから`strings.Join`を使った方がよさそうです

2022-12-12 12:04 UTC, mehm8128 commented on service/webhook.go
> +			message += fmt.Sprintf("- 関連するグループ: %s", resApp.Group.Name) + "\n"
```suggestion
			message += fmt.Sprintf("- 関連するグループ: %s\n", resApp.Group.Name)
```

2022-12-12 12:04 UTC, mehm8128 commented on service/webhook.go
> +			}
あとタグと同じように、``でtargetの名前を囲うのがよさそう

2022-12-12 12:07 UTC, mehm8128 commented
コミットを分けられているのは分かりやすくなってよいのですが、コミットメッセージについて
>PR名は不要なので、詳細に箇条書きで書いてあるものをそれぞれ別のコミットにする

と言及したところ、今`Update webhook.go`ってなってるところに修正の内容を書いてほしいです(descriptionはあんまり使わない気がします)(多分Github上でコミットするとデフォルトで`Update webhook.go`みたいになるんだと思いますがそこをいい感じに変えてみてください)

2022-12-14 05:37 UTC, karo1111111 commented
了解しました。ありがとうざいます。そのようにやってみます!(今CLIで作業するとエラーがおこり上手くいかないのでgithub上でやっていますが、問題が解決出来次第そちらでやるようにします)

2022-12-14 06:55 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("への支払い\n    - 支払い金額: 計%d円\n,      (一人当たりの支払い金額: 計%d円\n", -len(resApp.Target)*resApp.Amount, -resApp.Amount)
確かに…Paiza Ioでfmt.Printfとして試してみます。

2022-12-14 07:05 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("への支払い\n    - 支払い金額: 計%d円\n,      (一人当たりの支払い金額: 計%d円\n", -len(resApp.Target)*resApp.Amount, -resApp.Amount)
実際に打ち出してみて、合計金額と一人あたりの金額を、改行せずに横に並べたほうがみやすく感じたので変更していいでしょうか?

2022-12-14 12:59 UTC, mehm8128 reviewed
これ直したらここは大体よさそうです！
あとこれ↓が忘れられてそうなので対応お願いします(よく分からなかったら聞いて下さい)
https://github.com/traPtitech/Jomon/pull/627#issuecomment-1312509986

2022-12-14 12:59 UTC, mehm8128 commented on service/webhook.go
> +			}
箇条書き形式の`- `が入っていなさそうなので、最初に`message += "- "`みたいなのを入れる必要がありそうです👀

2022-12-14 12:59 UTC, mehm8128 commented on service/webhook.go
> +			targets := make([]string, len(resApp.Target))
`resApp.Target`だと1になってしまうのでresAppsの長さの方がよさそうです

2022-12-14 12:59 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("への支払い\n    - 支払い金額: 計%d円\n,      (一人当たりの支払い金額: 計%d円\n", -len(resApp.Target)*resApp.Amount, -resApp.Amount)
良さそうです👌

2022-12-14 14:51 UTC, mehm8128 commented on service/webhook.go
> +			}
というか全部ひとまとめにして
```
- `%s`への支払い〜
```
みたいに書けそう

2022-12-14 14:53 UTC, mehm8128 commented on service/webhook.go
> +			}
その前に、これだと`mehm8128 karo xxpoxx`みたいになってしまう気がします

2022-12-14 14:54 UTC, mehm8128 commented on service/webhook.go
> +			}
https://github.com/traPtitech/Jomon/pull/626#discussion_r1043284096
ここで言ったのと同じですね

2022-12-16 07:09 UTC, karo1111111 commented on service/webhook.go
> +			}
すみません…[↑](https://github.com/traPtitech/Jomon/pull/626#:~:text=2%20days%20ago-,%23626%20(comment),-%E3%81%93%E3%81%93%E3%81%A7%E8%A8%80)の後半部分をまた忘れていました…

2022-12-16 08:16 UTC, karo1111111 commented
[ここ](https://github.com/traPtitech/Jomon/pull/626#:~:text=%E3%81%A6%E4%B8%8B%E3%81%95%E3%81%84)-,%23627%20(comment),-service/webhook.go)について、新規にpull requestをしましたが、大丈夫だったでしょうか。確認していただけるとありがたいです。

2022-12-16 08:19 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sへの支払い\n    - 支払い金額: 計%d円(一人当たりの支払い金額: 計%d円)\n", targets, -len(resApps)*resApp.Amount, -resApp.Amount)
`targets`ではなくて`strings.Join(targets," ")`ですかね
他のところも同様だと思います

2022-12-16 08:22 UTC, mehm8128 commented
> [ここ](https://github.com/traPtitech/Jomon/pull/626#:~:text=%E3%81%A6%E4%B8%8B%E3%81%95%E3%81%84)-,%23627%20(comment),-service/webhook.go)について、新規にpull requestをしましたが、大丈夫だったでしょうか。確認していただけるとありがたいです。

Webhook関連という点で同じなので、PRを新たに生やす必要はない気がします
`e.Use`だと全てのリクエストに対して実行されてしまう気がするので(if文で分岐するので実行される内容的に問題はないですが)、[ここらへん](https://github.com/traPtitech/Jomon/blob/3f8ac5f9f2210067fc76b1eecfebee68ea1b1cc3/router/router.go#L44-L55)と同じようにtransactionのルーティング部分に追加するのがよさそうです

2022-12-17 09:01 UTC, karo1111111 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sへの支払い\n    - 支払い金額: 計%d円(一人当たりの支払い金額: 計%d円)\n", targets, -len(resApps)*resApp.Amount, -resApp.Amount)
なるほど…確かにそうですね…

2022-12-17 10:09 UTC, karo1111111 commented
すみません…router.goについてよくわからない部分が多く質問させていただいてもいいでしょうか?
・58行目`apiComments := api.Group("/transactions", h.CheckLoginMiddleware)`について、`next echo`とはなんでしょうか。
・60行目`apiComments.GET("", h.GetTransactions)`など`apiComments.■■("", ■■)`の形のコードについて、ここでは何が行われているのでしょうか。
お忙しいところ本当にすみません…

2022-12-17 12:21 UTC, mehm8128 commented
- [ここらへん](https://md.trap.jp/NnJwKWAyQiadR9zxGQEGSQ#checklogin%E9%96%A2%E6%95%B0)の話ですかね
- [ここ](https://md.trap.jp/Wys22vj0RMqzBMnep-63QA#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E4%BD%9C%E6%88%90)でやっているように、第一引数がパス、第二引数がそのパスにリクエストがきたときに実行される関数です
apiGroupを使うと、今回なら`transacitons/:transactionID`にGETリクエストがきたときに`h.GetTransaction`を実行、みたいにネストさせることができます

[apiGroupの名前がおかしい](https://github.com/traPtitech/Jomon/issues/628)のも、ついでにここで修正しちゃっていい気がします

2022-12-17 17:57 UTC, karo1111111 commented
なるほど…ありがとうございます!
すみません、もう一つよろしいでしょうか。h.CheckAdminMiddlewareはどのような働きをしているのでしょうか?

2022-12-17 23:48 UTC, mehm8128 commented
`h.CheckAdminMiddleware`について
`sess, err := session.Get(h.SessionName, c)`でsessionを取得し、
`_, ok := sess.Values[sessionUserKey].(*User)`でそのセッションに`"user"`をkeyとするvalueが含まれているかを確認し、
含まれていればログイン済み、そうでなければ未ログインと判断しているんだと思います

`apiComments := api.Group("/transactions", h.CheckLoginMiddleware)`
は`/transactions`から始まるものは全てそれを実行するようになってる気がするので、それ以下の階層で再びチェックする必要がない気もしますけど、とりあえず消さなくて大丈夫です

2022-12-20 03:14 UTC, karo1111111 commented
ログイン済み、未ログインを判断する理由はなんでしょうか。

また、
> Webhook関連という点で同じなので、PRを新たに生やす必要はない気がします

その場合のcommitの仕方がわからないです…お手数をおかけして申し訳ありませんが、教えていただけますでしょうか。

2022-12-20 03:19 UTC, karo1111111 commented
また、requestの方でGETリクエストの時、middleware.BodyDump(service.WebhookEventHandler)を入れなくても動く理由を教えていただけますか?

2022-12-20 04:40 UTC, mehm8128 commented
> ログイン済み、未ログインを判断する理由はなんでしょうか。
> 

ログインしている=traP部員であることを確認できる、なのでtraP部員であると確認できない人がJomonの情報を取得したり、データを書き換えたりできないようにするためです。

> また、
> 
> > Webhook関連という点で同じなので、PRを新たに生やす必要はない気がします
> 
> その場合のcommitの仕方がわからないです…お手数をおかけして申し訳ありませんが、教えていただけますでしょうか。

このブランチ(`transaction-webhook`)に`webhook.go`をcommitしたときと同じように`router.go`をcommitすればできるはずです。

2022-12-20 04:43 UTC, mehm8128 commented
> また、requestの方でGETリクエストの時、middleware.BodyDump(service.WebhookEventHandler)を入れなくても動く理由を教えていただけますか?

動いているのではなく、GETリクエストが送られたときはtraQのチャンネルにWebhookからメッセージを送信する必要がないため、入れていません。requestのGETリクエストは申請(依頼)を取得するためのAPIなので、取得される度にメッセージを送信する必要はないからです

2022-12-20 07:33 UTC, karo1111111 commented
> このブランチ(transaction-webhook)にwebhook.goをcommitしたときと同じようにrouter.goをcommitすればできるはずです。

[#639](https://github.com/traPtitech/Jomon/pull/639#issuecomment-1354368107)にcommitすることになりそうなのですが、大丈夫でしょうか?

2022-12-20 07:36 UTC, mehm8128 commented
> > このブランチ(transaction-webhook)にwebhook.goをcommitしたときと同じようにrouter.goをcommitすればできるはずです。
> 
> [#639](https://github.com/traPtitech/Jomon/pull/639#issuecomment-1354368107)にcommitすることになりそうなのですが、大丈夫でしょうか?

日本語がよくなかった
「このブランチ(transaction-webhook)に」というのは「webhook.goをcommitしたとき」にかかってるのではなくて(これにもかかってるけど)、「`router.go`をcommit」の方にかけたつもりでした
つまり、`transaction-webhook`ブランチに`router.go`をcommitしてください

2022-12-20 07:38 UTC, karo1111111 commented
[これ](https://github.com/traPtitech/Jomon/blob/transaction-webhook/router/router.go)を利用してしまっても大丈夫ですか?

2022-12-20 07:40 UTC, mehm8128 commented
はい、そのファイルに変更を加えてcommitしてください

2022-12-20 07:48 UTC, karo1111111 commented
レビューよろしくお願いいたします。

2022-12-26 13:47 UTC, mehm8128 commented
conflict起きてるので、Tagsの構造体をTagにrenameする方向で解消をお願いします

2022-12-27 06:24 UTC, karo1111111 commented
了解しました!
commitしました。レビューよろしくお願いします。

2022-12-27 07:13 UTC, mehm8128 commented on router/router.go
> +	e.Use(middleware.BodyDump(service.WebhookEventHandler))
一旦これ消してほしいです(各ルーティングで使っているのでここで使う必要がとりあえずはないです、後で全体の構造を修正する可能性がありますが)

2022-12-28 15:03 UTC, karo1111111 commented on router/router.go
> +	e.Use(middleware.BodyDump(service.WebhookEventHandler))
すみません…、消し忘れていました…

2022-12-28 16:15 UTC, mehm8128 commented
まだconflict起きてますね
`RequestApplication`の構造体はv2ブランチ、`TransactionRequestApplication`の構造体はtransaction-webhookブランチの変更を取り込むようにするのがよさそうです

2022-12-28 16:18 UTC, mehm8128 commented on service/webhook.go
> +			}
tagsのfor文みたいにちょっとだけ簡潔に書けそうです
`for i, resApp := range resApps {`
みたいな感じで

2023-01-02 11:20 UTC, mehm8128 commented
https://github.com/traPtitech/Jomon/pull/626#issuecomment-1366766184
conflictだけ直してもらえればマージできそうです！🙏

2023-01-02 11:23 UTC, karo1111111 commented
すみません…conflictしている箇所を確認する方法ってありますか?

2023-01-02 11:24 UTC, mehm8128 commented
masterブランチをマージしようとすればconflictが発生するはずです

2023-01-02 13:40 UTC, karo1111111 commented
`RequestApplication`の構造体についてなのですが、v2ブランチの変更を取り込む方針にするのはなぜでしょうか?
(transaction-webhook側で`Amount`と`Tags`が、v2ブランチ側で`Tags`と`Targets`が、それぞれ定義されているのですが、int型のものが一つも定義されていないv2ブランチに合わせるのが厳しい気がします。また、int型の`Amount`またはそれに準じるものを定義し、さらにv2ブランチ側に合わせようとすると、`Amount`,`Tags`,`Targets`の3つが残ることになりそうですが、この場合ただ単にtransaction-webhook側に余分な`Targets`が増えただけのような状態になっているように感じてしまいます。こちらの理解が間違っている可能性もかなりあるので教えていただけるとありがたいです…)

2023-01-02 13:47 UTC, mehm8128 commented
requestとtransactionで`Target`の定義が違うからですね
requestでは各targetに`Amount`が入っているので、それの合計をrequestの`Amount`として計算します(いくつか前のPRで修正されたので、v2ブランチをmergeするタイミングで反映されると思います)
それに対してtransactionでは`Target`はstringなので、`Amount`は別で定義しています

2023-01-02 13:48 UTC, karo1111111 commented
なるほど…ありがとうございます!!

2023-01-04 08:41 UTC, karo1111111 commented
遅くなってしまいすみません…RequestApplicationの構造体についてconflict解消しました。レビューよろしくお願いいたします。
また、transaction-webhookブランチの変更を取り込むTransactionRequestApplicationの構造体については、そのままにしておいて大丈夫なのでしょうか。

2023-01-04 08:46 UTC, mehm8128 commented
今commitしてもらったやつについてなのですが、conflictを解消しつつv2ブランチをmergeすればもっと簡単に修正できるはずで、commitしてもらったやつだとTargetの構造体がv2ブランチと変わってしまっていたり中身の処理がv2ブランチと変わってしまっていたりしてよくないので、直してほしいです

>transaction-webhookブランチの変更を取り込むTransactionRequestApplicationの構造体については、そのままにしておいて大丈夫なのでしょうか。

conflictが残った状態だとGithub上でmergeができないので、そちらも解消するようにお願いします

2023-01-05 14:48 UTC, mehm8128 approved these changes
よさそうです！
お疲れさまでした

2023-01-05 15:01 UTC, karo1111111 commented
いろいろと教えていただき本当にありがとうございます!!!

2023-01-06 06:34 UTC, cskd8 requested changes
現行のまま実際に試すとpanicしますね
> [PANIC RECOVER] runtime error: index out of range [0] with length 0

スライスで取るのはまあ無理だと思うのでちゃんとPUTとPOSTの場合に分けてください。

2023-01-06 06:34 UTC, cskd8 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
`fmt.Sprintf`である必要がありません。
go-staticcheckでcheckしてください(VSCodeならGoの拡張機能に入っていると思います)

2023-01-06 06:34 UTC, cskd8 commented on service/webhook.go
> +		if err != nil {
エラーチェックの位置がおかしい
直後でお願いします

2023-01-06 06:34 UTC, cskd8 commented on service/webhook.go
> +				message += fmt.Sprintf("- `%s`への支払い\n    - 支払い金額: %d円\n", resApp.Target, -resApp.Amount)
この書き方(\nのあとに空白4つ入れて...のこと)だとどういう文面かわかりづらいのでRequestのように+していく形で書き直してほしいです。
ほかのこの書き方のとこも同様

2023-01-06 06:34 UTC, cskd8 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sからの振込\n    - 受け取り金額: 計%d円(一人当たりの受け取り金額: 計%d円)\n", strings.Join(targets, " "), len(resApps)*resApp.Amount, resApp.Amount)
これ毎回忘れてるんですけど結局これの金額の計算なんでしたっけ、@mehm8128 に確認したいかも

2023-01-06 06:35 UTC, cskd8 commented
bot-console.trap.jp で適当にwebhook作って、投稿先を#team/SysAd/Jomon/devとかにしていろいろ試してみてください。docker-compose.ymlに環境変数を設定すれば動きます。

2023-01-06 06:39 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sからの振込\n    - 受け取り金額: 計%d円(一人当たりの受け取り金額: 計%d円)\n", strings.Join(targets, " "), len(resApps)*resApp.Amount, resApp.Amount)
部費など複数人分一気に作成したときに、人数分メッセージ投稿するとやばいので1つにまとめてるやつです

2023-01-06 06:43 UTC, cskd8 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sからの振込\n    - 受け取り金額: 計%d円(一人当たりの受け取り金額: 計%d円)\n", strings.Join(targets, " "), len(resApps)*resApp.Amount, resApp.Amount)
@mehm8128 
1つのトランザクションに関する`POST`、`PUT`で例えばA社、B社がTargetsでAmountが100になってたらA社に100円、B社に100円を意味するってことであってるよね？それなら大丈夫そう

2023-01-06 06:53 UTC, mehm8128 commented on service/webhook.go
> +				message += fmt.Sprintf("- %sからの振込\n    - 受け取り金額: 計%d円(一人当たりの受け取り金額: 計%d円)\n", strings.Join(targets, " "), len(resApps)*resApp.Amount, resApp.Amount)
そうですね、一番最初に書いてもらってる通り、PUTの場合は忘れてたので別で考えないといけなさそうですが

2023-01-06 19:15 UTC, karo1111111 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
初歩的な質問ですみません…[How to use the staticcheck commandの記事](https://staticcheck.io/docs/running-staticcheck/cli/)参考に`staticcheck`ターミナルに打てばいいのかと思ったのですが、`zsh: command not found:`になるので使い方間違えた気がします…go-staticcheckでのcheckの仕方教えていただけるとありがたいです…

2023-01-06 19:38 UTC, karo1111111 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
今ターミナル開かなくても勝手に出てきたことに気が付きました…

2023-01-09 03:30 UTC, mehm8128 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
これは`fmt.Sprintf`を使う必要がないのではなくて、
```
tags[i] = fmt.Sprintf("`%s`", tag.Name)
```
にする必要があります

2023-01-09 03:30 UTC, mehm8128 commented
最後のcommitで前3つのcommitの差分全部戻っちゃってる気がします

2023-01-19 05:24 UTC, karo1111111 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
すみません…`fmt.Sprintf`を使う必要がある理由を教えていただけるとありがたいです(そもそも`tag.Name`自体がstring型かつ一要素なので`fmt.Sprintf`でまとめて文字列にする必要ないのかと思っていました)

2023-01-19 06:30 UTC, mehm8128 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
https://github.com/traPtitech/Jomon/pull/626#discussion_r1022231305
これを実現するためですね

2023-01-19 12:00 UTC, karo1111111 commented on service/webhook.go
> +				tags[i] = fmt.Sprintf(`%s`, tag.Name)
なるほど…タグ表記にしていたの忘れていました…ありがとうございます…

2023-01-19 12:41 UTC, karo1111111 commented
すみません…PUTとPOSTの場合に分けるというのをもう少し詳しく教えてほしいです…
PUTとPOSTの違いについては調べたのですが、そもそもwebhook.go上のどこでそれらのメソッドに対応しているのかがわかりません。

2023-01-19 13:49 UTC, mehm8128 commented
> すみません…PUTとPOSTの場合に分けるというのをもう少し詳しく教えてほしいです… PUTとPOSTの違いについては調べたのですが、そもそもwebhook.go上のどこでそれらのメソッドに対応しているのかがわかりません。

`c.Request().Method == http.MethodPost`とかでPUTかPOSTか、みたいなのを判断しています
で、今回POSTの場合は配列で返すのでいいのですが、PUTの場合は単体で返すので(Swagger参照)最初から`resBody`を`resApp`に`json.Unmarshal`する必要がありそうです
そこを場合分けでいい感じにしてほしいです

2023-01-20 01:37 UTC, karo1111111 commented
なるほど、ありがとうございます!

2023-02-11 00:37 UTC, karo1111111 commented
遅くなってしまい本当にすみません。PUTにしてもPOSTにしても返すものって`message`(string)型ではないでしょうか?
(となるとresBodyをresAppにjson.Unmarshalするという作業をわざわざ入れなくてももともとstring型の単体で
返すので大丈夫なのかなと思ってしまいました。おそらく色々理解を間違えている状態で、そのために何をやればいいのかうまく理解できていない状況にあると思われます。「PUTにしてもPOSTにしても`message`(string)型単体返すので場合わけをする意味がわからない」のどこが間違っているのか教えていただけますでしょうか?)

2023-02-11 00:38 UTC, karo1111111 commented
また、話が変わるのですが、エラーハンドリング
```
err := json.Unmarshal(resBody, &resApps)
if err != nil {
　return
        }
```
で行われている処理の内容(どう動いているか)がわかっていないので教えていただけるとありがたいです

2023-02-11 01:35 UTC, mehm8128 commented
> 遅くなってしまい本当にすみません。PUTにしてもPOSTにしても返すものって`message`(string)型ではないでしょうか? (となるとresBodyをresAppにjson.Unmarshalするという作業をわざわざ入れなくてももともとstring型の単体で 返すので大丈夫なのかなと思ってしまいました。おそらく色々理解を間違えている状態で、そのために何をやればいいのかうまく理解できていない状況にあると思われます。「PUTにしてもPOSTにしても`message`(string)型単体返すので場合わけをする意味がわからない」のどこが間違っているのか教えていただけますでしょうか?)

「返すもの」というのはこのwebhookで返す通知の内容ということで合ってますか？(合っている前提で書くので違っていたら教えてください)
まず、`resBody`、`resApp`というのは↑のwebhookで返す"res"ではありません。このwebhook関数がどのような流れで動くかというと、
1. transactionのPOST、PUTリクエストがフロントエンドから送られてくる
1. サーバーがそのリクエストに応じた処理をし、結果を返す(PUTに成功したらPUT後のtramsactionを返す、など)
1. ↑で返したものが`resBody`となってこの関数に引数として渡される
1. `resBody`は`[]byte`で渡されるので扱いやすいように`Json.Unmarshal`でスライス・構造体に変換する
1. ↑の構造体を使ってwebhookの通知内容を作り、送信する

なので、最終的にwebhookの通知として返すものとして扱うのはstringのメッセージでいいのですが、2.のときにPOSTで返すのはスライス、PUTで返すのは構造体なため、`Json.Unmarshal`後に変換される内容が異なるので場合分けする必要があると思います

2023-02-11 01:36 UTC, mehm8128 commented
> また、話が変わるのですが、エラーハンドリング
> 
> ```
> err := json.Unmarshal(resBody, &resApps)
> if err != nil {
> 　return
>         }
> ```
> 
> で行われている処理の内容(どう動いているか)がわかっていないので教えていただけるとありがたいです

これは`resBody`を`Json.Unmarshal`した結果を`resApps`に渡し、変換する際にエラーが出たらエラーハンドリングしています

2023-02-13 05:15 UTC, karo1111111 commented
ありがとうございます！

 >1. transactionのPOST、PUTリクエストがフロントエンドから送られてくる
>2. サーバーがそのリクエストに応じた処理をし、結果を返す(PUTに成功したらPUT後のtramsactionを返す、など)
>3. ↑で返したものがresBodyとなってこの関数に引数として渡される
>4. resBodyは[]byteで渡されるので扱いやすいようにJson.Unmarshalでスライス・構造体に変換する
>5. ↑の構造体を使ってwebhookの通知内容を作り、送信する

これを理解していなかったのでとても助かりました…

スライスにJson.Unmarshalするとどういう状態になるのでしょうか？(resApps(TransactionRequestApplication))の形から外れることになると思うのですが、どのようになるかのイメージができていないです

2023-02-14 00:49 UTC, mehm8128 commented
> ありがとうございます！
> 
> > 1. transactionのPOST、PUTリクエストがフロントエンドから送られてくる
> > 2. サーバーがそのリクエストに応じた処理をし、結果を返す(PUTに成功したらPUT後のtramsactionを返す、など)
> > 3. ↑で返したものがresBodyとなってこの関数に引数として渡される
> > 4. resBodyは[]byteで渡されるので扱いやすいようにJson.Unmarshalでスライス・構造体に変換する
> > 5. ↑の構造体を使ってwebhookの通知内容を作り、送信する
> 
> これを理解していなかったのでとても助かりました…
> 
> スライスにJson.Unmarshalするとどういう状態になるのでしょうか？(resApps(TransactionRequestApplication))の形から外れることになると思うのですが、どのようになるかのイメージができていないです

`resApps`は`resApp`ではないので、`TransactionRequestApplication`ではなくて`[]TransactionRequestApplication`ですね
なのでそのままスライスの状態で`resApps`に渡すことができると思います

2023-02-15 04:11 UTC, karo1111111 commented
理解が遅くて申し訳ないです…また的外れな理解をしている可能性があるので確認してもよろしいでしょうか。
現状PUTの場合もresBodyからresApps(スライス)にjson.Unmarshalしようとしているため、resBodyをresApp(構造体)にjson.Unmarshalする、という解釈でよろしいでしょうか。

2023-02-15 10:32 UTC, mehm8128 commented
> 理解が遅くて申し訳ないです…また的外れな理解をしている可能性があるので確認してもよろしいでしょうか。 現状PUTの場合もresBodyからresApps(スライス)にjson.Unmarshalしようとしているため、resBodyをresApp(構造体)にjson.Unmarshalする、という解釈でよろしいでしょうか。

そういうことで合っています！説明能力皆無で申し訳ないです

2023-02-17 02:50 UTC, karo1111111 commented
resBodyをJson.Unmarshalした結果を渡しているのは`err := json.Unmarshal`この部分ということであっているのでしょうか？

https://github.com/traPtitech/Jomon/pull/626?notification_referrer_id=NT_kwDOBnK3LbQ0ODAwNTE4ODc0OjEwODE4MTI5Mw#issuecomment-1426560399

2023-02-17 03:14 UTC, karo1111111 commented
また、申請が複数人かつPUtの場合、一つの構造体の中にどのような形で値が収められているのでしょうか

2023-02-17 04:47 UTC, mehm8128 commented
> resBodyをJson.Unmarshalした結果を渡しているのは`err := json.Unmarshal`の部分ということであっているのでしょうか？ (以前コメントしていただいたのですが若干理解に不安があり質問させていただきました)

合っています！


> また、申請が複数人かつPUtの場合、一つの構造体の中にどのような形で値が収められているのでしょうか

これややこしいんですけど、フロントエンドからサーバーに送るときは複数人でPOSTできるのですが、サーバーでDBに保存するのは1つ1つ保存しているので、PUTするときは複数人は渡さずに1人分だけ送られてきます

2023-02-17 04:51 UTC, karo1111111 commented
了解しました！ありがとうございます！

2023-02-17 05:03 UTC, karo1111111 commented
レビューよろしくお願いいたします

2023-02-17 15:21 UTC, mehm8128 reviewed
修正したら動作確認もお願いします🙏

2023-02-17 15:21 UTC, mehm8128 commented on service/webhook.go
> +				}
ここPUTとPOSTで共通しているので、if文の外でまとめたいですね
一番最初にresApp宣言すると上手くいきそうです

2023-02-17 15:21 UTC, mehm8128 commented on service/webhook.go
>  			}
ここらへんも共通化したいけど厳しそうですね...
それぞれ変数にまとめておくようにすれば順番気にしなくて済むからいい感じになりそうな気もするけどとりあえずこのままで大丈夫そうです

2023-02-19 12:28 UTC, karo1111111 commented
>修正したら動作確認もお願いします🙏

dockerでしょうか…?(本当に何も知らなくてすみません…)

2023-02-19 12:56 UTC, mehm8128 commented
> > 修正したら動作確認もお願いします🙏
> 
> dockerでしょうか…?(本当に何も知らなくてすみません…)

あれ、前にwebhookの動作確認やってませんでしたっけ
xxpoxxさんが言っていたようにtraQでwebhook作成して環境変数入れて〜みたいなやつ

2023-02-19 13:36 UTC, karo1111111 commented
>適当に自分がオーナーのwebhookを作って、投稿先をJomonのrandomとかここにしてそのWebhookのキーを環境変数に含めてからtransactionを作成すると試せると思います

の
>そのWebhookのキーを環境変数に含めてからtransactionを作成すると試せると思います

↑の部分がわからず、そこから一旦後回しにしたままできていないです、本当にすみません…

2023-02-19 13:46 UTC, mehm8128 commented
> > 適当に自分がオーナーのwebhookを作って、投稿先をJomonのrandomとかここにしてそのWebhookのキーを環境変数に含めてからtransactionを作成すると試せると思います
> 
> の
> 
> > そのWebhookのキーを環境変数に含めてからtransactionを作成すると試せると思います
> 
> ↑の部分がわからず、そこから一旦後回しにしたままできていないです、本当にすみません…

なるほどです
僕もJomonのローカルでのサーバーの立ち上げ方あんまり分かっていないので、xxpoxxさんに聞いてみてほしいです🙏

2023-02-19 13:51 UTC, karo1111111 commented
了解です！ほんと何もわかってなくてすみません…

2023-02-19 13:52 UTC, karo1111111 commented
了解です！ほんと何もわかってなくてすみません…

2023-02-19 13:55 UTC, mehm8128 commented
> 了解です！ほんと何もわかってなくてすみません…

全体的にこちらが説明不足なのが悪いので気にしなくて大丈夫です👍

2023-02-27 03:19 UTC, karo1111111 commented
WebhookテスターでWebhookシークレットを設定してtraQにメッセージを送ることはできたのですが、これで動作確認として良いのでしょうか?`webhook_test.go`を作って`make test`する必要があるか教えていただけるとありがたいです

2023-02-27 04:29 UTC, mehm8128 commented
> WebhookテスターでWebhookシークレットを設定してtraQにメッセージを送ることはできたのですが、これで動作確認として良いのでしょうか?`webhook_test.go`を作って`make test`する必要があるか教えていただけるとありがたいです

テストは書かなくて大丈夫だと思いますが、transactionを色々なパターンで作成&修正してwebhookが正常に投稿されるかの確認もしてほしいです

2023-02-27 04:32 UTC, karo1111111 commented
transactionの作成本法がわからないです。

```
message="メッセージ本文"
signature=$(echo -n "$message" | openssl sha1 -hmac "Webhookシークレット")

curl -X POST -H "Content-Type: text/plain; charset=utf-8" -H "X-TRAQ-Signature: $signature" -d "$message" https://q.trap.jp/api/v3/webhooks/{コピーしたWebhook ID}
```

ここらへんのコマンドを使うのでしょうか?ただ、どこに数、取引先などを設定すれば良いかがわかっていないです。

2023-02-27 04:36 UTC, mehm8128 commented
https://md.trap.jp/Wys22vj0RMqzBMnep-63QA#Postman%E3%81%A7%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88
postmanでできると思います多分

2023-02-27 04:37 UTC, karo1111111 commented
ありがとうございます！

2023-08-16 11:24 UTC, mehm8128 approved these changes
まだリファクタリングできそうな箇所はいくつかあるのですが、一旦マ－ジします
ありがとうございました

2023-08-16 11:30 UTC, merged