getMeでDBを叩くように変更
traPtitech/Jomon pull request #763
Opened 2024-06-07 14:10 UTC by comavius

#725
- getMeでセッションからユーザーを取ってくる実装からDBからに変更
- DBにユーザーが存在しない場合にセッションのユーザーをDBに追加

2024-06-07 15:10 UTC, Pugma commented on router/user.go
> +	user_in_session, ok := sess.Values[sessionUserKey].(User)
めちゃ横槍で申し訳ないけど、プライベートな変数はローワーキャメルケースが標準な気がします
```suggestion
	userInSession, ok := sess.Values[sessionUserKey].(User)
```

2024-06-08 03:14 UTC, H1rono commented on router/user.go
> +	user_in_session, ok := sess.Values[sessionUserKey].(User)
:koreni_natteru:

2024-06-08 03:19 UTC, H1rono requested changes

2024-06-08 03:19 UTC, H1rono commented on router/user.go
> +	}
おかしい
`UserRepository.GetUserByID`があるのでそちらを使うべきです

https://github.com/traPtitech/Jomon/blob/444568f7d797d6976b03d238d91a9960a178f1df/model/user.go#L23

userが存在しない場合は何かしらのerrが返ってくるはずなので、それに応じて後に処理を続けてください

2024-06-08 03:19 UTC, H1rono commented
とりあえずこれ
あとテストの方を直す必要があります

2024-07-09 09:58 UTC, H1rono requested changes
まずは変数名をcamelCaseにしてください

2024-11-08 15:26 UTC, H1rono requested changes
`if err != nil`で`return nil, err`とするのは忘れずにお願いします :pray:

2024-11-08 15:26 UTC, H1rono commented on router/user.go
> +	}
これいらないです、もっとDBを信じるべき
ユーザーが見つからなかったら作成するくだりもいりません、`AuthCallback`部分でDBに追加しているため

https://github.com/traPtitech/Jomon/blob/6b2f353a620bebbc70927aab986bc2ab8aeace9d/router/auth.go#L85-L97

2024-11-08 16:13 UTC, H1rono requested changes

2024-11-08 16:13 UTC, H1rono commented on router/user.go
> +	}
`ent.IsNotFound`の時だけ`http.StatusNotFound`を返す処理を足してください

ref:

https://github.com/traPtitech/Jomon/blob/60dcf5f06d9add3f468f930a9ad1ac33819dd1f4/router/auth.go#L72

2024-11-08 16:52 UTC, H1rono requested changes
テスト頑張ってください

```
--- FAIL: TestHandlers_GetMe (0.00s)
    --- FAIL: TestHandlers_GetMe/Success (0.00s)
        user.go:95: Unexpected call to *mock_model.MockUserRepository.GetUserByID([context.Background.WithValue(sessions.contextKey, *sessions.Registry) c[76](https://github.com/traPtitech/Jomon/actions/runs/11745765123/job/32723973343?pr=763#step:8:77)069f6-ae57-40ee-be7d-b7674589867a]) at /home/runner/work/Jomon/Jomon/router/user.go:95 because: there are no expected calls of the method "GetUserByID" for that receiver
```

2024-11-14 15:11 UTC, H1rono commented on model/user.go
> +	DeletedAt   *time.Time `json:"deleted_at"`
この変更は必要なんでしょうか？使ってないように見えるんですが

2024-11-14 15:17 UTC, Hueter57 commented on model/user.go
> +	DeletedAt   *time.Time `json:"deleted_at"`
手元で実行したら、こんな感じにエラー出ました
```
--- FAIL: TestHandlers_GetMe (0.00s)
    --- FAIL: TestHandlers_GetMe/Success (0.01s)
        user_test.go:334: 
                Error Trace:    /home/kohsuke/SysAd/Jomon/router/user_test.go:334
                Error:          Not equal: 
                                expected: "{\"id\":\"7a045fc6-0a22-4b71-b989-93527fef1afc\",\"name\":\"9LcsCLBUWB7xgcntarNB\",\"display_name\":\"aRN8KgouLCcUuD9QtnUY\",\"admin\":true,\"created_at\":\"2024-11-15T00:15:44.088301571+09:00\",\"updated_at\":\"2024-11-15T00:15:44.088301571+09:00\",\"deleted_at\":null}"
                                actual  : "{\"ID\":\"7a045fc6-0a22-4b71-b989-93527fef1afc\",\"Name\":\"9LcsCLBUWB7xgcntarNB\",\"DisplayName\":\"aRN8KgouLCcUuD9QtnUY\",\"Admin\":true,\"CreatedAt\":\"2024-11-15T00:15:44.088301571+09:00\",\"UpdatedAt\":\"2024-11-15T00:15:44.088301571+09:00\",\"DeletedAt\":null}"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -{"id":"7a045fc6-0a22-4b71-b989-93527fef1afc","name":"9LcsCLBUWB7xgcntarNB","display_name":"aRN8KgouLCcUuD9QtnUY","admin":true,"created_at":"2024-11-15T00:15:44.088301571+09:00","updated_at":"2024-11-15T00:15:44.088301571+09:00","deleted_at":null}
                                +{"ID":"7a045fc6-0a22-4b71-b989-93527fef1afc","Name":"9LcsCLBUWB7xgcntarNB","DisplayName":"aRN8KgouLCcUuD9QtnUY","Admin":true,"CreatedAt":"2024-11-15T00:15:44.088301571+09:00","UpdatedAt":"2024-11-15T00:15:44.088301571+09:00","DeletedAt":null}
                Test:           TestHandlers_GetMe/Success
```

2024-11-14 16:06 UTC, H1rono commented on model/user.go
> +	DeletedAt   *time.Time `json:"deleted_at"`
変更前は`user`の型が`router.User`だった(`model.User`ではなく)ので上手くできてたっぽいですね、ここでもそれに合わせて`model.User`型から`router.User`型への変換を行って欲しいです(適宜↓のようなヘルパー関数を作ってください)

```go
package router

func userFromModelUser(u model.User) User { ... }
```

2024-11-14 23:15 UTC, H1rono commented on model/user.go
> +	DeletedAt   *time.Time `json:"deleted_at"`
(修正すべきはrouter内の、repositoryからuserを取ってきた後の処理です)

2024-11-20 04:26 UTC, H1rono approved these changes
LGTM
マージしておいてください

2024-11-20 17:04 UTC, merged