math/rand/v2
traPtitech/Jomon pull request #782
Opened 2024-07-05 09:17 UTC by Hueter57

close #736

2024-07-05 09:47 UTC, H1rono commented on testutil/random/ramdom.go
> +	for i := 0; i < n; i++ {
range over intにできます
#759 参照

2024-07-05 09:47 UTC, H1rono commented on testutil/random/ramdom.go
> +		result += string(letters[rand.IntN(len(letters))])
明らかに遅いのでなんか工夫したいです
参考: https://qiita.com/ono_matope/items/d5e70d8a9ff2b54d5c37

2024-07-05 09:47 UTC, H1rono commented on testutil/random/ramdom.go
>  	return n
`return rand.IntN(max)`にして下さい
`Numeric64`も同様

2024-07-06 00:52 UTC, H1rono submitted a review, later dismissed
LGTM
他にmath/rand使ってるところなければマージしてください

2024-07-06 05:15 UTC, Hueter57 commented
探したらmath/randを使っているところがもう一か所ありました
こっちも直してみます
https://github.com/traPtitech/Jomon/blob/ef91d11a1dfd312aa3110e8f11c5b9aa7157de48/router/auth.go#L129-L133

2024-07-17 03:54 UTC, H1rono requested changes
とりあえずこれだけ

2024-07-17 03:54 UTC, H1rono commented on router/auth.go
> +		}
```suggestion
		if _, err := crand.Read(b[:]); err != nil {
			panic(err)
		}
```

2024-07-17 14:03 UTC, H1rono approved these changes
LGTM

2024-07-17 14:03 UTC, merged