samber/loの適用
traPtitech/Jomon pull request #789
Opened 2024-08-04 17:41 UTC by Hueter57

#774

[lo.Reduce](https://github.com/samber/lo?tab=readme-ov-file#reduce)が使えそうといってたところはまだです。
issueでH1ronoさんが言っていたところはどう書けばいいかいまいちわからなかったです。
別のところですがここならlo.Reduce使えそうです。
https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/service/webhook.go#L120-L123

以下変更できなかった`append`を示しておきます。

https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/router/middleware.go#L26-L67

https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/router/request.go#L244-L255

https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/router/request.go#L452-L463

https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/router/transaction_test.go#L803

https://github.com/traPtitech/Jomon/blob/4f7fed37b740120c9376855a81bbbcbd156eeb32/router/transaction.go#L185-L229

2024-08-05 22:33 UTC, H1rono commented
とりあえずCIの対応お願いします

2024-08-09 12:49 UTC, H1rono commented
> issueでH1ronoさんが言っていたところはどう書けばいいかいまいちわからなかったです。

`&&`を使えばいいです

```go
result := lo.Reduce(targets, func(acc bool, target Target, _ int) bool {
    return acc && ...;
}, true)
```

`break`に比べて自明に効率が落ちるけど微々たるものなので

2024-09-25 19:13 UTC, H1rono requested changes
とりあえず、`ent`フォルダ以下は自動生成されたやつなので戻して欲しいです :pray:

2024-09-25 19:33 UTC, H1rono commented
や、嘘か
別のPRでrebaseした結果ですね、じゃあ戻さなくて大丈夫です

2024-10-01 16:01 UTC, H1rono commented
メモ
https://github.com/traPtitech/Jomon/compare/v2..samber_lo_adapt

2024-10-01 16:03 UTC, Hueter57 commented
レビュー出しましたけど`lo.Reduce`の変更がまだなのでやります

2024-10-01 16:33 UTC, Hueter57 commented
これで変更可能そうな`append`と`for`は全部`samber/lo`のものに変更できたと思います

2024-10-02 03:46 UTC, H1rono requested changes
概ね良さそうです

2024-10-02 03:46 UTC, H1rono commented on model/admin_impl.go
> +	admins := lo.Map(users, func(u *ent.User, insex int) *Admin {
`index`使ってないので、`_`で受け取るようにしてください
他のところも:pray:

```suggestion
	admins := lo.Map(users, func(u *ent.User, _ int) *Admin {
```

2024-10-02 03:46 UTC, H1rono commented on router/request.go
> +				return p
これ、`p`がtrueの場合は`target.PaidAt != nil`の真偽に関わらず`true`が返りますよね
この性質を、`||`演算子でうまく表現してほしいです

2024-10-02 03:46 UTC, H1rono commented on router/transaction_test.go
> +		res = append(res, &resOverview)
`res := []*Transaction{...}`の形にしてほしいです

2024-10-02 14:28 UTC, H1rono approved these changes
LGTM :thumbsup:

2024-10-02 14:28 UTC, merged